### PR TITLE
fix(experiments): experiment bucketing should liberally match on region-free languages

### LINKED ISSUE #2217: Email preferences not showing up in German
It was reported to me by marketing that email preferences are not showing up in German.

English:
image

German:
image

I'm not quite sure why. I have not had the chance to verify this but the screenshots convinced me.

### PR DESCRIPTION
**Pull request by 6a68**
Some German language users were unable to access the email settings page
with the 'de-DE' language enabled. Previously, 'de' was allowed, but
'de-DE' was explicitly disallowed. This commit changes the matching
behavior to work as follows:

* Loosely match languages specified without a region: if 'de' is
given, then 'de', 'de-DE', and 'de-AT' will all match.

* Strictly match languages specified with a region: if 'zh-tw'
is given, then 'zh' and 'zh-cn' will not match.

Fixes #2217, see also #2332 for context.

### CODE REVIEW

File: packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js [hunk 1]
```diff
@@ -10,22 +10,24 @@
...
-  'id',
-  'pl',
-  'pt-br',
-  'ru',
-  'zh-tw',
-];
+// If only the language, not the region, is specified, then all regions
+// will be considered a match. For instance, 'de' will match 'de', 'de-de',
+// 'de-at', etc. #2217
+const AVAILABLE_LANGUAGES = ['de', 'en', 'es', 'fr', 'hu', 'id', 'pl', 'ru'];
```
Comment (6a68) [inline packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js]: Prettier made this formatting change, not me :-P

File: packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js [hunk 2]
```diff
@@ -10,22 +10,24 @@
...
-  'de',
-  'en',
-  'en-[a-z]{2}',
-  'es',
-  'es-[a-z]{2}',
-  'fr',
-  'hu',
-  'id',
-  'pl',
-  'pt-br',
```
Comment (shane-tomlinson) [inline packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js]: This one may be problematic because Brazillian Portuguese is significantly different to Portuguese from Portugal.

File: packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js [hunk 3]
```diff
@@ -10,22 +10,24 @@
...
-  'ru',
-  'zh-tw',
```
Comment (shane-tomlinson) [inline packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js]: Same here, assuming `zh` should apply to `zh-cn` is probably *not* the right thing to do as the `zh-tw` means Taiwan only, and `zh-cn` means China. The politics of sending newsletters tailored to Taiwan to Chinese users could be politically messy. Plus @l-hedgehog runs a separate Chinese stack where newsletters are specifically disabled. See https://github.com/mozilla/fxa/blob/7228646ae64fb7ddce9071e567c94b1041382bcd/packages/fxa-content-server/server/lib/configuration.js#L367 and https://github.com/mozilla/fxa/commit/5c42ab2b2a6012d60ff77e56ab7d69df52f2b7d4.

File: packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js [hunk 4]
```diff
@@ -10,22 +10,24 @@
...
-];
+// If only the language, not the region, is specified, then all regions
+// will be considered a match. For instance, 'de' will match 'de', 'de-de',
+// 'de-at', etc. #2217
+const AVAILABLE_LANGUAGES = ['de', 'en', 'es', 'fr', 'hu', 'id', 'pl', 'ru'];
 
-const AVAILABLE_LANGUAGES_REGEX = arrayToRegex(AVAILABLE_LANGUAGES);
+// If the region is specified, other regions will not match. For instance,
+// 'pt-br' will not match 'pt' or 'pt-pt'. #2217
+const AVAILABLE_REGIONS = ['pt-br', 'zh-tw'];
```
Comment (6a68) [inline packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js]: @shane-tomlinson Note that this change strictly matches languages where the region is specified, like 'pt-br' and 'zh-tw'. These will not match on the base language or other regional languages. The tests have been updated to verify this works as intended.

File: packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js (hunk 2 above)
Comment (6a68) [reply packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js]: Yup, note that this is the deleted line, not the new line.

File: packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js (hunk 3 above)
Comment (6a68) [reply packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js]: Yup, the new code will preserve the distinction and strictly match on `zh-tw`.

File: packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js [hunk 5]
```diff
@@ -10,22 +10,24 @@
...
+
+const AVAILABLE_LANGUAGES_REGEX = generateRegex(
+  AVAILABLE_LANGUAGES,
+  AVAILABLE_REGIONS
+);
+
+function generateRegex(langs, regions) {
+  const combined = langs.map(x => `${x}|${x}-[a-z]{2}`).concat(regions);
```
Comment (shane-tomlinson) [inline packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js]: 👍

**Comment by 6a68** [comment]
@davismtl Hey, so I think this version of the #2217 fix is what the marketing folks had in mind:

* for languages like `de`, also match on any specified subregion, like `de-DE` or `de-AT`
* for languages with a region like `zh-tw`, match only on that subregion

This change will enlarge the user group targeted by language-specific marketing experiments, though I don't know by how much.

Do you think we're good to land this change?

**Comment by 6a68** [comment]
@clouserw This is ready to land once we get signoff from Alex (hopefully won't bitrot while I'm out)

**Comment by davismtl** [comment]
Based on the Slack conversations, you and Shane seem to have aligned with Lauren so I'll give my thumbs up based on that.

**Comment by 6a68** [comment]
Thanks @davismtl! We can always tweak this later if the change has unintended consequences for targeting :+1:
