### PR TITLE
fix(oauth): mark devices that register with OAuth tokens as 'mobile'

### LINKED ISSUE #449: New Devices: deviceType is DESKTOP for OAuth clients
From https://github.com/mozilla/application-services/pull/676#issuecomment-478193600

> deviceType is DESKTOP for OAuth clients. We need to have ability to set device type to mobile when we first create a device record
perhaps allow passing a device type to ensureRegistered method? we'll just need to set it once when the record is created, and will never need to change it

@rfk thoughts on this?

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #449

### CODE REVIEW

File: packages/fxa-auth-server/lib/devices.js [hunk 1]
```diff
@@ -89,6 +89,11 @@ module.exports = (log, db, push) => {
       if (! deviceInfo.name) {
         deviceInfo.name = credentials.client && credentials.client.name || '';
       }
+      if (credentials.client && ! deviceInfo.type) {
```
Comment (shane-tomlinson) [inline packages/fxa-auth-server/lib/devices.js]: I'm assuming `credentials.client` is only set for OAuth registrations? It's not really clear how that gets set. If so, can you update the comment to that effect?
