### PR TITLE
fix(settings): use non-interpolated classnames on tooltip

### LINKED ISSUE #6777: [FxA-Settings] No message error displayed for a very long display name value
**Build**
Stage [Train 1.192.0]

**Affected platforms**
Windows 10 x64
Android 9
iOS 13.6 

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2.  Click on the "Add" button from "Display name" area.
3. Copy a long text (ie https://whiletrue.neocities.org/lte.html) and paste it into the “Display name” field.
4. Click “Save” button.

**Expected results**
A proper error message saying that the display name is too long is correctly displayed.

**Actual Results**
A red arrow appears over the “Display name” field and there is no error message displayed.

Screenshot_15

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2650)
┆Issue Number: FXA-2650

### PR DESCRIPTION
**Pull request by dannycoates**
fixes #6777

### CODE REVIEW

**Comment by dannycoates** [comment]
I verified the built css file contains the previously missing class names

File: packages/fxa-settings/src/components/Tooltip/index.tsx [hunk 1]
```diff
@@ -17,6 +17,21 @@ type TooltipProps = {
...
+  if (position === 'top') {
+    if (type === 'error') {
+      return 'caret-bottom-error';
+    }
+    return 'caret-bottom-default';
+  }
+  if (type === 'error') {
+    return 'caret-top-error';
+  }
+  return 'caret-top-default';
```
Comment (chenba) [inline packages/fxa-settings/src/components/Tooltip/index.tsx:32]: caret-top eh?  🤡

**Review by chenba — APPROVED** [review]
:shipit:
