### PR TITLE
fix(test): fix oauth functional test

### LINKED ISSUE #8281: Changing display name on new-settings should fire profile changed event
This is causing breakage in one of the oauth_permissions tests.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3377)
┆Issue Number: FXA-3377

### PR DESCRIPTION
**Pull request by dannycoates**
Ummmmmm. Local storage is not a good way to handle oauth permission prompts but fixing that is much different than fixing the test case.

fixes #8281

### CODE REVIEW

File: packages/fxa-content-server/tests/functional/settings_v2/lib/helpers.js [hunk 1]
```diff
@@ -24,7 +25,7 @@ async function navigateToSettingsV2(remote) {
 
   await openPage(EMAIL_FIRST, selectors.ENTER_EMAIL.HEADER, remote);
   await fillOutEmailFirstSignIn(email, password, remote);
-
+  await testElementExists(selectors.SETTINGS_V2.APP);
```
Comment (vbudhram) [inline packages/fxa-content-server/tests/functional/settings_v2/lib/helpers.js:28]: The `remote` object needs to be passed as last param to these helper methods.

Comment (dannycoates) [reply packages/fxa-content-server/tests/functional/settings_v2/lib/helpers.js:28]: how did this work for me locally?! 🤦

**Review by vbudhram — APPROVED** [review]
