### PR TITLE
fix(avatar): update avatar image cropper to work effectively at all window sizes

### LINKED ISSUE #674: Avatar crop UI is uncentered on small screens/mobile
child of https://github.com/mozilla/fxa-content-server/issues/6261

(Originally reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1246138 for the specific case of the first-run flow)

STR: 
- As a logged-in user, visit https://accounts.firefox.com/settings, edit your avatar, and upload a new picture in order to access the /settings/avatar/crop screen.
- Make your window really short.

The resulting cropper UI is off-center like so:
screen shot 2016-02-08 at 13 06 40

If you make the window bigger a different set of styles kick in and it looks fine:
screen shot 2016-02-08 at 13 06 31

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-782)
┆Issue Number: FXA-782

### PR DESCRIPTION
**Pull request by jodyheavener**
Closes #674

This should address the avatar image cropper at smaller window sizes.
This was actually a bit of a doozy, since the cropper sizing was hard coded. The remedies I've used are:

- Update all the cropper component styles to be a little more fluid.
- Remove the ability to specify explicit vertical and horizontal gutters, instead relying on the calculated width of the wrapper versus the size of the cropping box.
- Position accordingly on page load and on window resize (debounced).

[Here's a demo video](https://imgur.com/v2qU6AK) of the cropping container at various window sizes.

Screen Shot 2020-03-07 at 9 36 04 PM

### CODE REVIEW

File: packages/fxa-content-server/app/scripts/lib/cropper.js [hunk 1]
```diff
@@ -44,19 +39,37 @@ function Cropper(options) {
...
+    const maxLength = this.exportLength * 2;
     if (img.width > maxLength || img.height > maxLength) {
-      var scale = maxLength / Math.max(img.width, img.height);
+      const scale = maxLength / Math.max(img.width, img.height);
       img = this.resize(img, scale);
     }
     this.setImageSrc(img.src, img.width, img.height);
   }
+
+  setTimeout(() => {
```
Comment (jodyheavener) [inline packages/fxa-content-server/app/scripts/lib/cropper.js]: I spent more time than I'd like to admit trying to debug an issue where the cropper is checking for element rect values before the DOM was finished laying out elements, so this is the result -- forcing the cropper to perform its checks after initial layout and execution is finished.

File: packages/fxa-content-server/app/scripts/lib/cropper.js [hunk 2]
```diff
@@ -44,19 +39,37 @@ function Cropper(options) {
   if (!options.container) {
     throw new Error('A container element is required');
   }
+
   this._setupElements(options.container);
 
+  window.addEventListener(
```
Comment (LZoog) [inline packages/fxa-content-server/app/scripts/lib/cropper.js]: This is looking _so much better_, we do need to remove the event listener though, otherwise when you close the cropper and resize settings it's still present. :( 

See my comment here: https://github.com/mozilla/fxa/pull/3763#discussion_r364926864

File: packages/fxa-content-server/app/scripts/lib/cropper.js [hunk 3]
```diff
@@ -44,19 +39,37 @@ function Cropper(options) {
...
+    'resize',
```
Comment (LZoog) [inline packages/fxa-content-server/app/scripts/lib/cropper.js]: This is looking _so much better_, we do need to remove the event listener though, otherwise when you close the cropper and resize settings it's still present. :( 

See my comment here: https://github.com/mozilla/fxa/pull/3763#discussion_r364926864

Comment (jodyheavener) [reply packages/fxa-content-server/app/scripts/lib/cropper.js]: @LZoog I've gone ahead and destroyed the event listener when you close the cropper.

File: packages/fxa-content-server/app/scripts/lib/cropper.js [hunk 4]
```diff
@@ -33,30 +30,45 @@ function Cropper(options) {
...
+    const maxLength = this.exportLength * 2;
     if (img.width > maxLength || img.height > maxLength) {
-      var scale = maxLength / Math.max(img.width, img.height);
+      const scale = maxLength / Math.max(img.width, img.height);
       img = this.resize(img, scale);
     }
     this.setImageSrc(img.src, img.width, img.height);
   }
+
+  setTimeout(() => {
```
Comment (LZoog) [inline packages/fxa-content-server/app/scripts/lib/cropper.js]: I tried a few things here too without much luck. Can we add a comment above for justification?

File: packages/fxa-content-server/app/scripts/lib/cropper.js [hunk 5]
```diff
@@ -110,18 +122,43 @@ Cropper.prototype._setupElements = function(container) {
     $sliderEl.val(this.scale);
     this.onZoomIn();
   });
+};
+
+Cropper.prototype.destroy = function(container) {
```
Comment (LZoog) [inline packages/fxa-content-server/app/scripts/lib/cropper.js]: I think we can leave an empty parameter here, otherwise I get a `'container' is declared but its value is never read.`

File: packages/fxa-content-server/app/scripts/views/settings/avatar_crop.js [hunk 6]
```diff
@@ -131,6 +126,14 @@ const View = FormView.extend({
...
     this.logViewEvent('zoom.range');
   },
+
+  _returnToAvatarChange() {
+    this.cropper.destroy();
+  },
+
+  _returnToSettings() {
+    this.cropper.destroy();
+  },
```
[the remark this answers is not in the document]
Comment (LZoog) [reply packages/fxa-content-server/app/scripts/views/settings/avatar_crop.js]: @jodyheavener this is my bad, I think this should be the last change before this sucker finally gets merged. `destroy()` above didn't work because I _meant_ to use `remove()`. 🤦‍♀️

You should be able to remove `_returnToAvatarChange()`, `_returnToSettings()`, and `this.cropper.destroy();` on line 96 and do this instead:

```
  remove() {
    this.cropper.destroy();
  }
```

I just tested it and it looks like it's working for me.

[the remark this answers is not in the document]
Comment (jodyheavener) [reply packages/fxa-content-server/app/scripts/views/settings/avatar_crop.js]: You are correct. I've updated accordingly!
