### PR TITLE
fix(payments): set PaymentErrorView action button background color an…

### LINKED ISSUE #10163: [subplat] Buttons from error page look inactive
**Affected browser versions:**

* All Chrome;

**Affected FxA versions:**

* 1.213.1;

**Prerequisites:**

* Have the a VPN set to Germany location;
* Have an FxA account with no active subscription;

**Steps to reproduce:**
1. Open VPN homepage https://www-dev.allizom.org/de/products/vpn/;
2. Click “Get Mozilla VPN” and choose any plan;
3. Fill all mandatory fields and use a credit card from Romania to subscribe.
4. Observe “Try again” button;

**Expected result:**

* The button is blue and active.

**Actual result:**

* The button is grayed out.

**Notes:**

* The  button is active, only looks disabled because of the color.
* Reproducing for all buttons from error pages;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3861)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16013/Screenshot+from+2021-08-19+13-06-08.png">Screenshot from 2021-08-19 13-06-08.png</a>

### PR DESCRIPTION
**Pull request by biancadanforth**
…d margin-bottom correctly

Because:

* The action button was grey and there was no white space between it and the legal links below.

This commit:

* Gives the action button a class of primary-button, so that it's default and hover state are shades of blue and adds a margin-bottom of 40px.

Closes #10163

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)
Screen Shot 2021-08-23 at 2 36 03 PM

### CODE REVIEW

File: packages/fxa-payments-server/src/components/PaymentErrorView/index.tsx [hunk 1]
```diff
@@ -26,7 +26,7 @@ const retryButtonFn = (onRetry: PaymentErrorViewProps['onRetry']) => (
   <Localized id="payment-error-retry-button">
     <button
       data-testid="retry-link"
-      className="button retry-link"
+      className="button retry-link primary-button"
```
Comment (chenba) [inline packages/fxa-payments-server/src/components/PaymentErrorView/index.tsx:29]: huh!  So this is a change and not a fix?  It was grey in the past?  I thought it was blue.  🤷

Comment (biancadanforth) [reply packages/fxa-payments-server/src/components/PaymentErrorView/index.tsx:29]: It was definitely blue at some point in the past. But CSS is tricksy as if some change to CSS causes this rule to be less specific, it will be ignored in favor of the more specific one for example.
