### PR TITLE
fix(subs): Add display_name field to subhub create subscription API

### LINKED ISSUE #1597: Include display_name in subhub create subscription payload
It has been determined that subsystems need a user's name to process data creation correctly.  This issue is to request that the profile display_name is included in the body of the  POST /customer/{uid}/subscriptions request.  There is currently an pending PR to accept this value in Subhub .

### PR DESCRIPTION
**Pull request by 6a68**
Fixes #1597.

-----

original WIP description:

* Not yet able to get tests running locally; pushing to CI to see if the
tests run there.

* Looks like the payments-server already gets the full profile from the
profile-server, so it's just a matter of passing the display name field
from payments-server to auth-server, and then from auth-server to
subhub.

### CODE REVIEW

File: packages/fxa-auth-server/lib/subhub/client.js [hunk 1]
```diff
@@ -207,6 +210,7 @@ module.exports = function(log, config) {
           if (err.statusCode === 400 || err.statusCode === 402) {
             throw error.rejectedSubscriptionPaymentToken(err.message, err);
           }
+          // TODO: update with whatever the error response is for missing display_name.
```
Comment (philbooth) [inline packages/fxa-auth-server/lib/subhub/client.js]: I think you'll need to tweak the condition above as this is one possible meaning of the `400` response.

Ref:
https://github.com/mozilla/subhub/blob/e530fcb67339c8b41035ec2a67b06d23c4ef97b2/subhub/subhub_api.yaml#L133-L136

Comment (philbooth) [reply packages/fxa-auth-server/lib/subhub/client.js]: (you can see elsewhere we resort to interrogation of `err.message`, I guess this will need more of the same sadly)

File: packages/fxa-auth-server/test/remote/subscription_tests.js [hunk 2]
```diff
@@ -154,14 +155,16 @@ describe('remote subscriptions:', function() {
       assert.deepEqual(result, []);
     });
 
+    // TODO: not sure if any changes need to be made here
```
Comment (philbooth) [inline packages/fxa-auth-server/test/remote/subscription_tests.js]: Yeah, looks like `display_name` is not returned, so there's nothing to assert here:

https://github.com/mozilla/subhub/blob/e530fcb67339c8b41035ec2a67b06d23c4ef97b2/subhub/subhub_api.yaml#L438-L479

File: packages/fxa-auth-server/lib/subhub/client.js (hunk 1 above)
Comment (philbooth) [reply packages/fxa-auth-server/lib/subhub/client.js]: Actually ignore me, given that it's `required` in the API here, I guess you don't need that condition after all?

Comment (6a68) [reply packages/fxa-auth-server/lib/subhub/client.js]: Ah, cool! Thanks, I'll remove the TODO

**Comment by 6a68** [comment]
@philbooth OK, got the tests green! Mind taking a last look?
