### PR TITLE
fix(payments): date formatting on subscription list

### LINKED ISSUE #1751: date formatting inconsistent
other screens show July 09, 2020 format
this screen shows 07/09/2020 format

which is the correct format for FxA/Mozilla?

Screen Shot 2019-07-11 at 2 05 26 PM

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #1751

### CODE REVIEW

File: packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx [hunk 1]
```diff
@@ -76,6 +76,11 @@ export const PaymentUpdateForm = ({
     .unix(customerSubscription.current_period_end)
     .format('MM/DD/YYYY');
 
+  const expirationDate = dayjs()
+    .set("month", exp_month)
+    .set("year", exp_year)
+    .format("MMMM, YYYY");
```
Comment (lmorchard) [inline packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx]: The issue didn't give us an exact format, but I'd guess we don't want a comma here.

File: packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx [hunk 2]
```diff
@@ -76,6 +76,12 @@ export const PaymentUpdateForm = ({
     .unix(customerSubscription.current_period_end)
     .format('MM/DD/YYYY');
 
+  // https://github.com/iamkun/dayjs/issues/639
+  const expirationDate = dayjs()
+    .set("month", Number(exp_month))
+    .set("year", Number(exp_year))
+    .format("MMMM YYYY");
```
Comment (shane-tomlinson) [inline packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx]: Just read this, are there locales where this ordering is swapped? I know we don't have to worry about it for MVP, something to keep in mind when expanding into other countries.
