### PR TITLE
fix(customs): Standardize the log format in fetchIPReputation

### LINKED ISSUE #769: Odd log body with fetchIPReputation (fxa-customs-server)
```
{
	"err": {
		"body": "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n",
		"status": 502
	},
	"hostname": "ip-172-31-8-48.us-west-2.compute.internal",
	"level": 50,
	"msg": "",
	"name": "customs-server",
	"op": "fetchIPReputation",
	"pid": 1,
	"rtime": "2.17",
	"v": 0
}
```

`err` is usually a String, rather than an Object

### PR DESCRIPTION
**Pull request by shane-tomlinson**
`err` is expected to be a string all the time, if a request to fetch IP reputation
failed an object was logged, which would cause problems when Stackdriver 
validates against its schema.

This change makes it so that failing HTTP requests to the IP reputation service 
log a string `err` and add a new `statusCode` field.

fixes #769

@jbuck, @mozilla/fxa-devs - r?

### CODE REVIEW

File: packages/fxa-customs-server/lib/reputationService.js [hunk 1]
```diff
@@ -51,13 +51,18 @@ var get = function (log, ipClient, ip) {
...
           rtime: getRequestTime(response) })
       } else {
-        var err = { status: response.statusCode, body: response.body }
-        log.error({ op: 'fetchIPReputation', ip: ip, err: err, rtime: getRequestTime(response) })
+        log.error({
+          err: response.body,
+          ip,
+          op: 'fetchIPReputation',
+          rtime: getRequestTime(response),
+          statusCode: response.statusCode,
```
Comment (shane-tomlinson) [inline packages/fxa-customs-server/lib/reputationService.js]: statusCode is also [used up here](https://github.com/mozilla/fxa/pull/809/files#diff-1c4367a4c81cd2d8ce8b37d310d13972R33), so I tried to stay consistent.
