### PR TITLE
fix(buttons): Add `Not now` button back to sms page

### LINKED ISSUE #3597: We removed "start browsing" on CAD page
This issue was filed because the user thought that CAD was required:
https://github.com/mozilla/fxa/issues/3594

I was surprised because we have a start browsing button on that page. We even have an issue open to measure usage of the "start browsing" link:
https://github.com/mozilla/fxa/issues/3022

I just went through the flow and it seems like we've removed the link:
image

Let's restore the "Start browsing" link. 

Note: Martin Lapatka also brought this to my attention this week. He reported that he knew folks who thought that this was required.

CC @ryanfeeley

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #3597 

From https://github.com/mozilla/fxa/issues/3597#issuecomment-563440152, I opted to use `Not now`. Clicking the link will take you to the FxA product page in the same window.

Screen Shot 2019-12-09 at 5 31 26 PM

### CODE REVIEW

File: packages/fxa-content-server/app/scripts/views/sms_send.js [hunk 1]
```diff
@@ -31,11 +33,19 @@ class SmsSendView extends FormView {
...
+    'click .btn-not-now': preventDefaultThen('gotoProductPage'),
+  });
+
   getAccount() {
     // TODO - remove the `|| ...` when done with development
     return this.model.get('account') || this.user.getSignedInAccount();
   }
 
+  gotoProductPage() {
+    this.window.location.href = SmsSendView.FXA_PRODUCT_PAGE_URL;
```
Comment (shane-tomlinson) [inline packages/fxa-content-server/app/scripts/views/sms_send.js]: Can you just set the href of the anchor element? The [ExternalLinksMixin](https://github.com/mozilla/fxa/blob/3bbffd84da7139af2b6d1593141a1171f7c528ab/packages/fxa-content-server/app/scripts/views/mixins/external-links-mixin.js) is added to BaseView, it'll take care of flushing metrics for you and you won't need this extra code. Direct assignment of `window.location.href` like this doesn't take care of flushing metrics.

File: packages/fxa-content-server/app/tests/spec/views/sms_send.js [hunk 2]
```diff
@@ -158,6 +158,12 @@ describe('views/sms_send', () => {
         assert.lengthOf(view.$('.success'), 0);
       });
     });
+
+    it('renders `not now` links', () => {
+      return view.render().then(() => {
+        assert.lengthOf(view.$('.btn-not-now'), 1);
```
Comment (vbudhram) [inline packages/fxa-content-server/app/tests/spec/views/sms_send.js]: @shane-tomlinson if I do a `click()` on this element, it will redirect current window to the link. However, that will make all the next mocha tests fail since the page moved.

Is there a better way to test this? Maybe this test isn't needed?

Comment (shane-tomlinson) [reply packages/fxa-content-server/app/tests/spec/views/sms_send.js]: I'd just migrate this whole thing to the functional tests. Or stub out `navigateAway` before clicking.

Comment (shane-tomlinson) [reply packages/fxa-content-server/app/tests/spec/views/sms_send.js]: Maybe check the link is displayed in the functional tests but don't click it. We've had recent issues about tests failing because of external dependencies and minimizing those would be worthwhile.

File: packages/fxa-content-server/tests/functional/send_sms.js [hunk 3]
```diff
@@ -192,6 +193,13 @@ const suite = {
         .then(testElementExists(selectors.SMS_SEND.HEADER));
     },
 
+    'not now': function() {
+      return this.remote
+        .then(openPage(SEND_SMS_URL, selectors.SMS_SEND.HEADER))
+        .then(click(selectors.SMS_SEND.LINK_NOT_NOW))
+        .then(testUrlInclude('https://www.mozilla.org/'));
```
Comment (vbudhram) [inline packages/fxa-content-server/tests/functional/send_sms.js]: Navigating to the site 301s to the `en-US` version, it made sense to just check first part of url.

File: packages/fxa-content-server/app/tests/spec/views/sms_send.js (hunk 2 above)
Comment (vbudhram) [reply packages/fxa-content-server/app/tests/spec/views/sms_send.js]: Done!
