### PR TITLE
fix(tooltip): Update/remove inline password tooltip when password changes

### LINKED ISSUE #3486: Password fields are not validated inline with “Show password” option enabled
**Notes:**
This issue is a follow-up bug for #631

**Build:**
Stage [Train 1.151.0]

**Affected platforms:**
Windows 10 64-bit

**Steps to reproduce:**
1. Launch Firefox and click on the FxA toolbar menu button.
2. Type a new email address which does not have associated a Firefox Account..
3. Type an invalid email in the first password field.
4. Type a valid email in the second password field.
5. Enable the “Show password” option before the password error to be displayed.
6. Return to the first password field and insert the same password as the one typed in the second field.

**Expected results:**
“Passwords do not match” error is no longer displayed

**Actual Results:**
“Passwords do not match” error does not disappear even if the passwords are the same.

**Additional notes:**
- This issue was encountered on Firefox 70.0.1.
- I am attaching a video.

passwordsvalidation

### LINKED ISSUE #3489: (sign-up) Repeat password balloon no longer shows
I believe this is regression from https://github.com/mozilla/fxa/pull/3406. The balloon shows in commit 4a2420f21 before this was merged but no longer in e098929f4.

@ryanfeeley @davismtl do we want to rethink this now that we have the inline validation? When does it disappear?

With no inline validation but with balloon (sorry for cutoff):
pw-balloon

With inline validation and no balloon:
pw-balloon-noshow

### LINKED ISSUE #3504: Password Verification Tooltip Incorrectly Displayed
There's a timing(?) issue somewhere that's causing the not matching password tooltip to be displayed, even when the passwords are matching.

image

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #3504 
Fixes #3489
Fixes #3486

This PR updates the inline password validation rules to fix the above issues.

@LZoog you mentioned working on #3489 but I think I found an easy fix while working those other issues. I can flag you for review after adding tests here.

### CODE REVIEW

**Comment by LZoog** [comment]
👍 Sweet, thanks for taking care of these!

File: packages/fxa-content-server/app/scripts/views/sign_up_password.js [hunk 1]
```diff
@@ -78,12 +77,10 @@ const SignUpPasswordView = FormView.extend({
     );
   },
 
-  isValidEnd() {
-    if (!this._doPasswordsMatch()) {
-      return false;
-    }
+  onFormChange() {
```
Comment (vbudhram) [inline packages/fxa-content-server/app/scripts/views/sign_up_password.js]: This was the fix for https://github.com/mozilla/fxa/issues/3489, for some reason having the `keyup #vpassword` event caused the password info bubble to disappear. Instead, I hooked into the existing events that get trigger when form element changed.

File: packages/fxa-content-server/app/scripts/views/sign_up_password.js [hunk 2]
```diff
@@ -93,6 +90,9 @@ const SignUpPasswordView = FormView.extend({
         AuthErrors.toError('PASSWORDS_DO_NOT_MATCH'),
         false
       );
+    } else {
+      // Called to clear validation tooltips.
+      this.$(VPASSWORD_INPUT_SELECTOR).change();
```
Comment (vbudhram) [inline packages/fxa-content-server/app/scripts/views/sign_up_password.js]: This fixes other two issues. If the tooltip is on an element whose value does not change, the the validation rules to remove it were not triggered. Simple fix was to fake an element change.
