### PR TITLE
fix(error): keep zip field from erroring while user inputs

### LINKED ISSUE #3168: Over eager invalid handling on zip code input
Focus the zip code and start typing, when a single character is entered, the box is marked `invalid`. The box should only look to see if it's invalid on blur

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #3168

@lmorchard this seems like a simple way to get around the edge case you identified in your comment on that bug.

### CODE REVIEW

File: packages/fxa-payments-server/src/components/PaymentForm/index.tsx [hunk 1]
```diff
@@ -274,15 +274,17 @@ const validateName: OnValidateFunction = (value, focused) => {
 };
 
 const validateZip: OnValidateFunction = (value, focused) => {
-  let valid = true;
+  let valid = null;
```
Comment (lmorchard) [inline packages/fxa-payments-server/src/components/PaymentForm/index.tsx]: Looks like a type validation thing failed CI here - this should probably be `let valid = undefined;`

File: packages/fxa-payments-server/src/components/PaymentForm/index.tsx [hunk 2]
```diff
@@ -274,15 +274,17 @@ const validateName: OnValidateFunction = (value, focused) => {
...
   let error = null;
   value = ('' + value).substr(0, 5);
   if (!value) {
     valid = false;
     error = 'Zip code is required';
-  } else if (value.length !== 5) {
+  } else if (value.length !== 5 && !focused) {
     valid = false;
     error = 'Zip code is too short';
+  } else if (value.length == 5) {
```
Comment (lmorchard) [inline packages/fxa-payments-server/src/components/PaymentForm/index.tsx]: :+1: good thinking! I don't think this exact thing had occurred to me!
