### PR TITLE
fix(auth): always fetch latest stripe object to store

### LINKED ISSUE #10904: [subplat] Currency error message displayed when trying to update card information
**Affected versions**:

* All;

**Affected FxA versions**:

* 1.218.4;

**Prerequisites**:

* Be in a Mozilla VPN supported country (US);

**Steps to reproduce**:
1. Subscribe to Mozilla VPN monthly plan using Stripe and a US card (e.g. 4242424242424242);
2. Go to Subscription Management page for the same account;
3. Click on the “Change” button to update payment details (e.g. 4000056655665556);
4. Click on the “Update” button;
5. Observe the behaviour;

**Expected result**:

* The payment details are successfully updated. 

**Actual result**:

* “The currency of this subscription is not valid for the country associated with your payment” error message is displayed in the Payment section. The card number cannot be updated.

**Notes**:

* This is a major issue because the user is not able to update his payment information;
* Reproducible if using the same card number that was used for making the subscription;
* Reproducible for new and old users;
* Reproducible regardless of the currency;
* See the attached screenshot.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4171)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/17413/Screenshot+2021-11-02+at+17.47.12.png">Screenshot 2021-11-02 at 17.47.12.png</a>

### PR DESCRIPTION
**Pull request by bbangert**
Because:

* Webhooks may come out of order, or be triggered by requests we perform
  without storing the latest object.

This commit:

* Always stores the latest object from stripe in firestore.

Closes #10904

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

File: packages/fxa-auth-server/lib/payments/stripe.ts [hunk 1]
```diff
@@ -2454,7 +2454,12 @@ export class StripeHelper {
    */
   async processCustomerEventToFirestore(event: Stripe.Event) {
     const { data } = event;
-    const customer = data.object as Stripe.Customer;
+    const customer = await this.stripe.customers.retrieve(
+      (data.object as Stripe.Customer).id
+    );
+    if (customer.deleted) {
```
Comment (chenba) [inline packages/fxa-auth-server/lib/payments/stripe.ts:2460]: hmmm I noticed that the other set of handlers does not handle `customer.deleted`, so if we just return early here, we won't ever know that a customer has been deleted I think.

**Review by chenba — CHANGES_REQUESTED** [review]
I think we need to save the customer into Firestore on delete.

File: packages/fxa-auth-server/lib/payments/stripe.ts (hunk 1 above)
Comment (bbangert) [reply packages/fxa-auth-server/lib/payments/stripe.ts:2460]: Ah, good catch, because we will not have touched the record in Firestore.

**Review by chenba — APPROVED** [review]
💰
