### PR TITLE
fix(profile): use Inter Bold for the monogram font everywhere

### LINKED ISSUE #8210: Default avatar character is not centered
!image-2021-04-08-19-35-46-456.png!

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3346)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15956/image-2021-04-08-19-35-46-456.png">image-2021-04-08-19-35-46-456.png</a> | <a href="https://jira.mozilla.com/secure/attachment/16015/screenshot-1.png">screenshot-1.png</a>
┆Issue Number: FXA-3346

### PR DESCRIPTION
**Pull request by dannycoates**
Because system fonts don't have consistent alignment points across platforms we should stick with a single known font.

fixes #8210

### CODE REVIEW

File: packages/fxa-profile-server/lib/routes/avatar/default.js [hunk 1]
```diff
@@ -19,15 +25,20 @@ module.exports = {
       .response(
         `<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
         <defs>
+          <style>
+          @font-face{
+            font-family:"Inter";
+            src:url(data:application/font-woff;charset=utf-8;base64,${font}) format("woff");
```
Comment (vbudhram) [inline packages/fxa-profile-server/lib/routes/avatar/default.js:31]: In my local testing the new image is 150KB+ verses 1KB. Is there a different font or some optimization that could be done?

Comment (dannycoates) [reply packages/fxa-profile-server/lib/routes/avatar/default.js:31]: i just pushed an optimized font that's ~5kb

**Review by vbudhram — APPROVED** [review]
@dannycoates LGTM 👍🏽
