### PR TITLE
fix(sign-in/up): Display new Sync copy on force_auth and Sync mobile

### LINKED ISSUE #13424: [FxA optimizations] Old Sign in page displayed when signing in back to Sync after password change
**Build:**

Stage [Train 235]

**Affected platforms:**

Windows 10 64-bit

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

The user is signed in to Sync with the same account on two different devices.

**Steps to reproduce:**

1. On one of the devices (e.g. mobile device) go to Password section and click “Change“ button.
1. Fill in all the fields with valid data and click “Save“.
1. On the other device (e.g. desktop) click the “Firefox account” button in the toolbar.
1. Click “Account disconnected” and sign back in. 

**Actual result:**

The old “Sign in Continue to Firefox Sync” page is displayed.

**Expected result:**

The new “Enter your password for your Firefox account“ page is displayed.

**Notes:**

N/A

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5415)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/25540">old Sign in page displayed for Sync.gif</a>

### LINKED ISSUE #13425: [FxA optimizations] Old copies are displayed on mobile for "Enter your email Continue to Firefox Sync" and "Sign in Continue to Firefox Sync" pages
**Build:**

Stage [Train 235]

**Affected platforms:**

Android 12

iOS 15.4

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

N/A

**Steps to reproduce:**

1. Launch Firefox browser on mobile.
1. Tap on 3 dots menu and then on “Sign in to Sync”.
1. Tap on “Use email instead“.

**Actual result:**

“Enter you email Continue to Firefox Sync“ page is displayed instead of “Continue to Firefox accounts“ new page. 

**Expected result:**

“Continue to Firefox accounts“ new page is displayed.

**Notes:**

Same when user signs in - The “Sign in Continue to Firefox Sync“ page is displayed instead of “Enter your password for your firefox account“ new page.

Also the “Sync your passwords, tabs, and bookmarks….” copy is not displayed.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5416)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/25542">Screenshot_20220624-122553.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/25594">Screenshot_20220627-132704.png</a>

### PR DESCRIPTION
**Pull request by LZoog**
Because:
* New Sync copy was not displayed on the force_auth page, or when tapping 'Sign in to Sync' through mobile FF browser

This commit:
* Updates force_auth mustache accordingly
* Tweaks the service mixin to also check for serviceName
* Places 'Enter your password for your Firefox account' in one string for l10n on sign_in_password

fixes #13424
fixes #13425

### CODE REVIEW

File: packages/fxa-content-server/app/scripts/views/mixins/service-mixin.js [hunk 1]
```diff
@@ -32,7 +33,11 @@ export default {
       service,
       serviceName: subscriptionProductName || serviceName,
       serviceLogo,
-      isSync: this.relier.isSync(),
+      // relier.isSync() doesn't appear to get set from deeplink in mobile FF
+      // so also check serviceName, see #13425
+      isSync:
+        this.relier.isSync() ||
+        serviceName === Constants.RELIER_SYNC_SERVICE_NAME,
```
Comment (LZoog) [inline packages/fxa-content-server/app/scripts/views/mixins/service-mixin.js:40]: This was a bit of a weird one. I looked around at `isSync` in the codebase and found a comment in `reliers/base.js` that says, "Check if the relier is Sync for Firefox Desktop". Though, in most files, we're checking exclusively for `this.relier.isSync()`, and then in other places we check for `service === 'sync'` or we check against the `serviceName`.

I can see in the screenshot that QA provided that clearly, the `serviceName` is getting passed in and rendering correctly, so this _should_ fix that ticket. I originally changed the check to _just_ check for the serviceName, but it caused tests in other files to fail, and because Backbone I'm not sure if this is overwriting other `isSync` checks that are referencing `this.relier.isSync()`, like [this one](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/app/scripts/views/ready.js#L117) in `ready.js`. Having both checks seems safest so that's what I went with.

File: packages/fxa-content-server/app/scripts/views/mixins/service-mixin.js [hunk 2]
```diff
@@ -32,7 +33,11 @@ export default {
       service,
       serviceName: subscriptionProductName || serviceName,
       serviceLogo,
-      isSync: this.relier.isSync(),
+      // relier.isSync() doesn't appear to get set from deeplink in mobile FF
+      // so also check serviceName, see #13425
```
Comment (chenba) [inline packages/fxa-content-server/app/scripts/views/mixins/service-mixin.js:37]: > relier.isSync() doesn't appear to get set

I can't quite parse this.  Is `isSync` not there?

File: packages/fxa-content-server/app/scripts/views/mixins/service-mixin.js (hunk 1 above)
Comment (LZoog) [reply packages/fxa-content-server/app/scripts/views/mixins/service-mixin.js]: Ahh, things suddenly make sense and that's much cleaner so thanks. 😁

I updated my PR. I checked against `serviceName` since it was less logic as opposed to the permission scope but maybe you didn't mean that anyway with "value on that scope".

File: packages/fxa-content-server/app/scripts/views/mixins/service-mixin.js (hunk 2 above)
Comment (LZoog) [reply packages/fxa-content-server/app/scripts/views/mixins/service-mixin.js]: This was my poor attempt at trying to summarize what I said in my longer comment earlier. No longer applicable now so it was removed.

File: packages/fxa-content-server/app/scripts/templates/force_auth.mustache [hunk 3]
```diff
@@ -1,8 +1,16 @@
 <div id="main-content" class="card">
   <header>
     <h1 id="fxa-force-auth-header">
-      <!-- L10N: For languages structured like English, the second phrase can read "to continue to %(serviceName)s" -->
-      {{#t}}Sign in{{/t}} <span class="service">{{#t}}Continue to %(serviceName)s{{/t}}</span>
+      {{#isSync}}
+        {{#t}}Enter your password{{/t}}
+        <span class="description">
+          {{#t}}for your Firefox account{{/t}}
+        </span>
```
Comment (chenba) [inline packages/fxa-content-server/app/scripts/templates/force_auth.mustache:8]: I don't think we should break this into to two translatable strings.  The missing context for the second half could be confusing for the localisers.

**Review by chenba — CHANGES_REQUESTED** [review]
a standalone phrase of "for your Firefox account" will be confusing to localiser (or maybe not translatable for certain language grammars)

File: packages/fxa-content-server/app/scripts/templates/force_auth.mustache (hunk 3 above)
Comment (LZoog) [reply packages/fxa-content-server/app/scripts/templates/force_auth.mustache:8]: 👍 Good thinking, I forget in content-server we have to do that `{{#unsafeTranslate}}` bit.

**Review by chenba — APPROVED** [review]
👍
