### PR TITLE
fix(auth-server): compare message timestamp in milliseconds

### LINKED ISSUE #2956: [fxa-auth-server]: Fix inconsistent timestamp checks in sqs receiver
The SQS receiver does timestamp comparisons, but the timestamp from the database is in milliseconds, while the event createdAt is in seconds.

### PR DESCRIPTION
**Pull request by bbangert**
Fixes #2956

### CODE REVIEW

File: packages/fxa-auth-server/lib/subhub/updates.js [hunk 1]
```diff
@@ -99,14 +99,18 @@ class SubHubMessageProcessor {
       }
     }
 
+    // The createdAt in our db always has milliseconds, so we compare and store
+    // this value in milliseconds as this Stripe value is in seconds.
+    const messageCreatedAt = message.eventCreatedAt + 1000;
```
Comment (lmorchard) [inline packages/fxa-auth-server/lib/subhub/updates.js]: Did you mean *plus* 1000 or *times* 1000 here?

Comment (bbangert) [reply packages/fxa-auth-server/lib/subhub/updates.js]: I definitely meant *times*.

Comment (6a68) [reply packages/fxa-auth-server/lib/subhub/updates.js]: ouch.  reviewer fail
