### PR TITLE
fix(auth): use token handler for token endpoint

### LINKED ISSUE #10195: Token endpoint returns plans
The token endpoint was linked to the wrong handler function, it should be linked to the token handler.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3879)

### PR DESCRIPTION
**Pull request by bbangert**
Because:

* The token handler should be used for the token endpoint.

This commit:

* Uses the correct handler for the token endpoint.

Closes #10195

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

**Review by chenba — APPROVED** [review]
👍   Is there a test that verifies which function in the GoogleIapHandler is called when the request handler is called?  Feel like we should have something to catch this.

File: packages/fxa-auth-server/lib/routes/subscriptions/google.ts [hunk 1]
```diff
@@ -109,7 +109,8 @@ export const googleIapRoutes = (): ServerRoute[] => {
             .required(),
         },
       },
-      handler: (request: AuthRequest) => googleIapHandler.plans(request),
```
Comment (dannycoates) [inline packages/fxa-auth-server/lib/routes/subscriptions/google.ts:112]: 😬 how did i miss that?

**Comment by bbangert** [comment]
@chenba there isn't, nor for a bunch of other payment ones as well, runTest could probably do it. Though its a lot of test infra to rig up for a missed link like this.
