### PR TITLE
bug (content server): fix support form success message

### LINKED ISSUE #5298: Contact support confirmation popup message is incomplete
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with active subscription

#### Steps to reproduce
1. Open /subscriptions page: https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions
2. Click the “Contact Support” button
3. Fill out all fields and click “Send”
4. Observe confirmation popup message 

#### Expected result:
- There are no issues in the confirmation message..

#### Actual result:
The value of the “What are you contacting us about?” field is missing.

#### Notes:
- Reproducing for both (Firefox Guardian/Other) options.

for

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1875)
┆Issue Number: FXA-1875

### PR DESCRIPTION
**Pull request by jackiemunroe**
Because:
* the support form success message is missing the product value

This commit:
* fix the message creation function to reference the correct form value
* remove the 'FxA - ' prefix that is added for Zendesk Agents, to match mockups and to show users the value they selected accurately

fixes #5298

### CODE REVIEW

File: packages/fxa-content-server/app/scripts/views/support.js [hunk 1]
```diff
@@ -162,24 +159,28 @@ const SupportView = BaseView.extend({
...
 
-  formatProductName: function(name) {
+  formatProductName: function (name) {
     const productNamePrefix = 'FxA - ';
     return `${productNamePrefix}${name}`;
   },
 
-  submitButtonUIToggle: function() {
+  unformatProductName: function (name) {
+    const productNamePrefix = /^FxA - /;
```
Comment (chenba) [inline packages/fxa-content-server/app/scripts/views/support.js:173]: With this, the `FxA - ` prefix is defined in two places; we should move the one on line 168 out to a wider scope so this function can use it.  It also needn't to be regex.  The prepending always happens so we could just strip the prefix without searching.

File: packages/fxa-content-server/app/scripts/views/support.js [hunk 2]
```diff
@@ -162,24 +159,28 @@ const SupportView = BaseView.extend({
...
+    return name.replace(productNamePrefix, '');
+  },
```
Comment (chenba) [inline packages/fxa-content-server/app/scripts/views/support.js:175]: nit^2: newline here

File: packages/fxa-content-server/app/scripts/views/support.js (hunk 1 above)
Comment (jackiemunroe) [reply packages/fxa-content-server/app/scripts/views/support.js:173]: sounds good!
