### PR TITLE
fix(auth): enable a retry on backendServices

### LINKED ISSUE #10134: WError: A backend service request failed.
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/10024262/?referrer=github_plugin

```
EndpointError: pushbox.services.mozilla.com:443 error: read ECONNRESET
WError: A backend service request failed.
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/error.js", line 1464, in Function.AppError.backendServiceFailure
    return new AppError(
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/backendService.js", line 188, in sendRequest
    throw error.backendServiceFailure(
  ?, in runMicrotasks
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/backendService.js", line 239, in async Service.theServiceMethod [as retrieve]
    response = await sendRequest(
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/pushbox.js", line 145, in async Object.retrieve
    const body = await api.retrieve(uid, deviceId, query);
...
(7 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3851)

### PR DESCRIPTION
**Pull request by dannycoates**
closes #10134

### CODE REVIEW

File: packages/fxa-auth-server/lib/pool.js [hunk 1]
```diff
@@ -23,7 +23,7 @@ function Pool(uri, options = {}) {
     timeout: options.timeout || 5000,
     maxPending: options.maxPending || 1000,
     keepAlive: true,
-    maxRetries: 0,
```
Comment (bbangert) [inline packages/fxa-auth-server/lib/pool.js:26]: 😀

**Review by bbangert — APPROVED** [review]
