### PR TITLE
fix(tests): remove cross functional test dependency

### LINKED ISSUE #2003: Failing functional test: 'support form without active subscriptions - go to support form with an active subscription, successfully submits the form'
See https://circleci.com/gh/mozilla/fxa/54567#tests/containers/3

> × firefox on mac 18.7.0 - support form without active subscriptions - go to support form with an active subscription, successfully submits the form (21.221s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/6dbc32d4-0687-a948-a996-1e6d99bc50f7/element / {"using":"css selector","value":"div.product-payment"}] Unable to locate element: div.product-payment
    For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'stomlinson-30887', ip: '192.168.1.229', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '9.0.1'
    Driver info: driver.version: unknown
      at Command.<anonymous>  <tests/functional/lib/helpers.js:191:22>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:61:10>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:75:18>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:69:10>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:1333:8>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:61:10>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:1335:8>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:61:10>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:69:10>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:2358:6>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:61:10>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:69:10>
      at Test.go to support form with an active subscription, successfully submits the form [as test]  <tests/functional/support.js:51:10>
      at <src/lib/Test.ts:263:51>

This fails locally for me too.

### PR DESCRIPTION
**Pull request by chenba**
The test title was also incorrect previously.

Fixes #2003

### CODE REVIEW

File: packages/fxa-content-server/tests/functional/support.js [hunk 1]
```diff
@@ -36,7 +35,8 @@ registerSuite('support form without valid session', {
 
 registerSuite('support form without active subscriptions', {
   tests: {
-    'go to support form without active subscriptions, redirects to subscription management': function() {
+    'go to support form, redirects to subscription management': function() {
+      let email = TestHelpers.createEmail();
```
Comment (vladikoff) [inline packages/fxa-content-server/tests/functional/support.js]: hm does this have to be a `let` here? and below?

Comment (vladikoff) [reply packages/fxa-content-server/tests/functional/support.js]: @chenba yes see CI log:

> /home/circleci/project/packages/fxa-content-server/tests/functional/support.js
  39:11  error  'email' is never reassigned. Use 'const' instead  prefer-const
  54:11  error  'email' is never reassigned. Use 'const' instead  prefer-const

Comment (chenba) [reply packages/fxa-content-server/tests/functional/support.js]: Yeah, just plain ol' mistake. :(
