### PR TITLE
fix(metrics): update language property on Amplitude schema

### LINKED ISSUE #4783: Amplitude event failed validation.
https://sentry.prod.mozaws.net/operations/auth-prod/issues/7768105/

```
Amplitude event failed validation.
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1504)
┆Issue Number: FXA-1504

### PR DESCRIPTION
**Pull request by chenba**
This patch loosens the regular expression pattern on the language
property of the Amplitude event JSON schema.

The time property is also updated to be a positive integer as that is
what fxa-amplitude-send expects.

Fixes #4783 (FXA-1504)

### CODE REVIEW

File: packages/fxa-content-server/tests/server/amplitude-schema-validation.js [hunk 1]
```diff
@@ -121,12 +121,12 @@ registerSuite('amplitude json schema validation', {
...
       );
       assert.equal(
-        scope.setContext.args[0][1]['err']['message'],
+        scope.setContext.args[0][1]['error'],
         'QUUX IS NOT A VALID DEVICE ID'
       );
       assert.isTrue(
         mockSentry.captureMessage.calledOnceWith(
-          'Amplitude event failed validation.',
+          'Amplitude event failed validation: QUUX IS NOT A VALID DEVICE ID.',
```
Comment (jodyheavener) [inline packages/fxa-content-server/tests/server/amplitude-schema-validation.js:129]: so angry!

**Comment by chenba** [comment]
> 
> 
> While I'm not terribly familiar with this area your changes look reasonable. I'm curious, though, why the loosening was needed? I couldn't see in Sentry what the data looked like that made it explode.

The issue was with 3alpha language tags.  Most of the errors were from `ast`.  There are also some grandfathered-in tags that starts with a single letter.

Yeah I had to dig around in BigQuery and Amplitude to get an idea what language tags were causing the error. :(
