### PR TITLE
fix(auth-server): paypal customer fix script

### LINKED ISSUE #8544: Fix paypal customers affected by credit note misfire
Some users were affected by a credit note being issued to the account balance instead of refunding the paypal transaction id. A one-off script is needed to fix these customers, zero the account balance, and cancel any subscriptions not cancelled when they were refunded.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3479)
┆Issue Number: FXA-3479

### PR DESCRIPTION
**Pull request by bbangert**
Because:

* Credit notes issued as account balance aren't refunded in paypal
  correctly.

This commit:

* Locates invoices since launch that had a credit note applied that was
  credited to the balance instead of refunded and fixes the balance,
  issues a paypal refund, and cancels the subscription.

Closes #8544

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

File: packages/fxa-auth-server/scripts/paypal-refund-fixer.ts [hunk 1]
```diff
@@ -0,0 +1,182 @@
...
+      yield invoice;
+      count++;
+      if (limit && count >= limit) {
+        break;
+      }
+    }
+  }
+
+  async zeroAccountBalance(customer: stripe.Customer) {
+    if (customer.balance >= 0) {
```
Comment (bbangert) [inline packages/fxa-auth-server/scripts/paypal-refund-fixer.ts:67]: Positive amounts mean they owe us, negative amounts mean we owe them, which are the only ones we want to zero.

File: packages/fxa-auth-server/scripts/paypal-refund-fixer.ts [hunk 2]
```diff
@@ -0,0 +1,182 @@
...
+        balance: customer.deleted ? 0 : customer.balance,
+        subs: subs.length,
+        deleted: !!customer.deleted,
+      });
+      i++;
+
+      if (!customer.deleted) {
+        await this.zeroAccountBalance(customer);
+      }
+      if (subs.length === 1) {
```
Comment (dannycoates) [inline packages/fxa-auth-server/scripts/paypal-refund-fixer.ts:126]: subs can't ever be > 1? ... just checking

Comment (bbangert) [reply packages/fxa-auth-server/scripts/paypal-refund-fixer.ts:126]: They can, I've run a read-only version of this and only one customer managed to get 2 subs. We'll need to handle that customer separately so we don't want to cancel the sub just yet.

File: packages/fxa-auth-server/scripts/paypal-refund-fixer.ts [hunk 3]
```diff
@@ -0,0 +1,182 @@
...
+      return;
+    }
+    const zeroAmount = Math.abs(customer.balance);
+    await this.stripe.customers.createBalanceTransaction(customer.id, {
+      amount: zeroAmount,
+      currency: customer.currency!,
+    });
+  }
+
+  async issueRefund(invoice: stripe.Invoice) {
```
Comment (bbangert) [inline packages/fxa-auth-server/scripts/paypal-refund-fixer.ts:77]: This is almost identical to the issueRefund inside the paypalHelper, however since this runs as a script the stripeHelper updateInvoice here needs an await on it to ensure we don't skip one at the end.

File: packages/fxa-auth-server/scripts/paypal-refund-fixer.ts [hunk 4]
```diff
@@ -0,0 +1,182 @@
...
+        invoiceId: invoice.id,
+        customerId: customer.id,
+        balance: customer.deleted ? 0 : customer.balance,
+        subs: subs.length,
+        deleted: !!customer.deleted,
+      });
+      i++;
+
+      if (!customer.deleted) {
+        await this.zeroAccountBalance(customer);
```
Comment (dannycoates) [inline packages/fxa-auth-server/scripts/paypal-refund-fixer.ts:124]: Should this come after `issueRefund`, in case that fails? tbh i don't know enough context to know which should go first

File: packages/fxa-auth-server/scripts/paypal-refund-fixer.ts [hunk 5]
```diff
@@ -0,0 +1,182 @@
...
+        invoice.post_payment_credit_notes_amount === 0
+      ) {
+        continue;
+      }
+      yield invoice;
+      count++;
+      if (limit && count >= limit) {
+        break;
+      }
+    }
```
Comment (chenba) [inline packages/fxa-auth-server/scripts/paypal-refund-fixer.ts:63]: If I'm reading the limits correctly, this will only process a max of 100 customers per execution.  Are we going to run this script multiple times then?

Comment (bbangert) [reply packages/fxa-auth-server/scripts/paypal-refund-fixer.ts:63]: That's not actually used, I can remove it. We actually get everyone the first time, because we're using async iteration, and its 100 per batch.

**Review by chenba — APPROVED** [review]
Make sense to me

**Review by biancadanforth — APPROVED** [review]
Just added a few clarifying questions. Logic makes sense to me.

File: packages/fxa-auth-server/scripts/paypal-refund-fixer.ts [hunk 6]
```diff
@@ -0,0 +1,182 @@
...
+    });
+  }
+
+  async issueRefund(invoice: stripe.Invoice) {
+    const transactionId = this.stripeHelper.getInvoicePaypalTransactionId(
+      invoice
+    );
+    if (!transactionId) {
+      return;
+    }
```
[the remark this answers is not in the document]
Comment (bbangert) [reply packages/fxa-auth-server/scripts/paypal-refund-fixer.ts:83]: No reason, there must be one here, but this makes TypeScript happy since the method signature says it could be undefined.
