### PR TITLE
fix(password-balloon): Improve password strength balloon edgecases

### LINKED ISSUE #3465: Password Strength Bubble Not Displayed for a Short, Edited Password
#### STP
1. Enter a valid password so that password strength bubble goes away
1. Hold down backspace until the password is fewer than eight character
1. Quickly press tab to move to confirm password input

#### Expected

Password strength bubble automatically re-appears as the password is too short

#### Actual

Password strength bubble does not show when the user tab over to the confirm password field.  It does re-appear when the user try to submit the password.

image

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-575)
┆Priority: Medium
┆Issue Number: FXA-575

### LINKED ISSUE #3750: If user types password in sign-up and quickly tabs away when matching criteria, strength balloon persists
I believe this is an edge-case I didn't catch in #3724.

If a user types their password quickly enough and tabs before all 3 checks are shown, the password strength balloon doesn't disappear.

pw

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-845)
┆Priority: Medium
┆Issue Number: FXA-845

### PR DESCRIPTION
**Pull request by LZoog**
Fixes #3750 
Fixes #3465
Partial fix for #3575 (fixes the first issue mentioned)

Also:
- Fixes edgecase shown at the bottom of #3792
- The balloon now updates on keyboard paste. 🎉 While the balloon does not update on mouse paste, it _does_ update when you paste and then tab away (not new).

pw

### CODE REVIEW

File: packages/fxa-content-server/app/scripts/views/password_strength/password_strength_balloon.js [hunk 1]
```diff
@@ -55,14 +55,18 @@ class PasswordStrengthBalloonView extends BaseView {
     if (!this.model.validationError && !this.model.get('inputFocused')) {
       return this.hide();
     }
+    // OneVisibleOfTypeMixin uses 'show' to destroy any other
+    // tooltip-like views.
+    return this.show();
```
Comment (chenba) [inline packages/fxa-content-server/app/scripts/views/password_strength/password_strength_balloon.js]: We probably should update the function name now that it shows and hides.

File: packages/fxa-content-server/app/scripts/views/password_strength/password_with_strength_balloon.js [hunk 2]
```diff
@@ -24,8 +24,7 @@ const PasswordWithStrengthBalloonView = FormView.extend({
   events: {
     change: 'updateModelAfterDelay',
     focus: 'focusHandler',
-    keypress: 'updateModelAfterDelay',
-    blur: 'blurHandler',
+    keydown: 'updateModelAfterDelay',
```
Comment (chenba) [inline packages/fxa-content-server/app/scripts/views/password_strength/password_with_strength_balloon.js]: Doesn't a keydown also trigger a change event, which is handled by `updateModelAfterDelay` a couple lines up?

Comment (LZoog) [reply packages/fxa-content-server/app/scripts/views/password_strength/password_with_strength_balloon.js]: Ooo @chenba good call out - it doesn't look like we need `change` here at all. `keypress` also fired `updateModelAfterDelay` but this may have been missed due to the debounce. I took out `change` and readded `blur`, and passed the `event.type` to `updateModel` instead of using jQ to check if the el was out of focus. I also made a comment clearer, added a test for `inputFocused` on the model, and updated `shouldHide` to `hideOrShow`.

I checked all the edgecases and tried to break the thing and it's looking good to me. Clicking on password reveal all works as expected too.
