### PR TITLE
fix: capture GraphQL errors in field resolvers

### LINKED ISSUE #7059: GraphQL errors should be reported to Sentry
Errors in graphql field resolvers are not being reported to Sentry. They should be.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2778)
┆Issue Number: FXA-2778

### PR DESCRIPTION
**Pull request by bbangert**
Because:

* Interceptors for NestJS do not capture field resolvers due to how
  apollo-server runs the query/mutation before then running separate
  queries to resolve fields.

This commit:

* Hooks into an apollo-server request lifecycle hook made for error
  reporting to accurately report errors to Sentry that occur when
  resolving fields.

Closes #7059

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

File: packages/fxa-shared/nestjs/sentry/reporting.ts [hunk 1]
```diff
@@ -122,6 +122,10 @@ export function reportRequestException(
   excContexts: ExtraContext[] = [],
   request?: Request
 ) {
+  // Don't report already reported exceptions
```
Comment (bbangert) [inline packages/fxa-shared/nestjs/sentry/reporting.ts:125]: This is needed because the Sentry interceptor *and* the lifecycle hook error reporter are triggered by the same mutation/query level error.

File: packages/fxa-shared/nestjs/sentry/reporting.ts [hunk 2]
```diff
@@ -122,6 +122,10 @@ export function reportRequestException(
...
+  if ((exception as any).reported) {
```
Comment (jodyheavener) [inline packages/fxa-shared/nestjs/sentry/reporting.ts:126]: Maybe `exception`'s type could be changed to `exception: Error & { reported: boolean }` so we don't need to cast to `any`?

**Review by jodyheavener — APPROVED** [review]
R+ with a nit

File: packages/fxa-shared/nestjs/sentry/reporting.ts (hunk 2 above)
Comment (bbangert) [reply packages/fxa-shared/nestjs/sentry/reporting.ts:126]: Oh, nice call! Updated the type to avoid the casts.

File: packages/fxa-shared/nestjs/sentry/sentry.plugin.ts [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+          return;
+        }
+        for (const err of ctx.errors) {
+          // Only report internal server errors,
+          // all errors extending ApolloError should be user-facing
+          if (err instanceof ApolloError) {
+            continue;
+          }
+          // Skip errors with a status already set or already reported
+          if (err.originalError?.status) {
```
Comment (chenba) [inline packages/fxa-shared/nestjs/sentry/sentry.plugin.ts:34]: I see a `reported` property set in the file above, but I don't see it being checked here.  Unless I misunderstanding the comment, it should be checked here?
