### PR TITLE
fix(payment-server): cancel dialog loading indication in button

### LINKED ISSUE #2751: The modal is not displayed on multiple clicks on the "Cancel" subscription button
This was filed in the guardian repo by @SoftVision-LorandJanos. Re-posting here.

#### Affected versions:
- Firefox Release 69.0.1
- Firefox Beta 70.0b9
- Firefox Nightly 71.0a1

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.5
- Linux Ubuntu 16.04 (64-bit)

#### Prerequisites:
You have an active Guardian VPN subscription.

#### Steps to reproduce
1. Go to the [Manage Subscriptions](https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions).
2. Click on the "Cancel" button.
3. Check the box to confirm cancellation.
4. Click on the "Cancel Subscription" button multiple times.

#### Expected result:
- A modal is displayed with the title "We're sorry to see you go".

#### Actual result:
- The modal is not displayed.

#### Notes:
- On double or more clicks the user receives two cancellation confirmation mails, but not more than two. 

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/GUARDIAN-206)

### LINKED ISSUE #2988: The modal is not displayed on multiple clicks on the "Cancel" subscription button
See [this](https://github.com/mozilla/fxa-private/issues/77)

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #2988

### CODE REVIEW

File: packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx [hunk 1]
```diff
@@ -25,12 +25,14 @@ type SubscriptionItemProps = {
   updatePayment: Function;
   cancelSubscriptionMounted: Function;
   cancelSubscriptionEngaged: Function;
+  cancelSubscriptionStatus: any;
```
Comment (lmorchard) [inline packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx]: Instead of `any`, I think you should be able to use [a more specific `CancelSubscriptionFetchState` type](https://github.com/mozilla/fxa/blob/eaa4fa4cdd33b1435c9c7ede4afc654ff1e836ac/packages/fxa-payments-server/src/routes/Subscriptions/index.tsx#L75)

File: packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx [hunk 2]
```diff
@@ -124,6 +127,7 @@ type CancelSubscriptionPanelProps = {
   customerSubscription: CustomerSubscription;
   cancelSubscriptionMounted: Function;
   cancelSubscriptionEngaged: Function;
+  cancelSubscriptionStatus: any;
```
Comment (lmorchard) [inline packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx]: Same thing here, CancelSubscriptionFetchState should work as a type I think?

File: packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx (hunk 1 above)
Comment (meandavejustice) [reply packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx]: Thanks, meant to make a comment asking about that in my pr. Glad you caught it :)
