### PR TITLE
fix(auth): send Subscription Delete Email When User Deletes Fx Account

### LINKED ISSUE #12262: [subplat] Subscription cancellation emails not sent on FxA account deletion
**Background**

When a customer, with a subscription, deletes their FxA account, they should receive an email notifying them that their subscription has been cancelled.

**Steps to reproduce**

1. Create an FxA account
1. Sign up for a new subscription
1. Delete the FxA account on the Account page

**Expected result**

Receive a subscription cancellation email. (subscriptionAccountDeletion)

**Actual result**

Did not receive any email.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4764)

### PR DESCRIPTION
**Pull request by IvoJP**
Because:

* We want to notify a user that their subscriptions have been deleted when they delete their fx account

This commit:

* Updates the stripe event handler to send emails to accounts that have been deleted

Closes #12262

_Put an `x` in the boxes that apply_

- [X] My commit is GPG signed.
- [X] If applicable, I have modified or added tests which pass locally.
- [X] I have added necessary documentation (if appropriate).
- [X] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

**Review by StaberindeZA — APPROVED** [review]
LGTM.


Just a note for the JIRA <> Github integration to work, it looks like you need to add the `fxa-` before the JIRA number.

File: packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts [hunk 1]
```diff
@@ -428,15 +428,19 @@ export class StripeWebhookHandler extends StripeHandler {
       }
 
       const uid = customer.metadata.userid;
-      const account = await this.db.account(uid);
-
+      const account = await Account.findByUid(uid, { include: ['emails'] });
```
Comment (chenba) [inline packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts:431]: Why does this need the `{ include: ['emails'] }' option?

Comment (IvoJP) [reply packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts:431]: It doesn't. I copied the call from the function below. I can remove it.

**Comment by IvoJP** [comment]
> LGTM.
> 
> Just a note for the JIRA <> Github integration to work, it looks like you need to add the `fxa-` before the JIRA number.

noted!
