### PR TITLE
fix(metrics): remove declined sync engines from amplitude events

### LINKED ISSUE #938: Track CWTS screen view in Amplitude
When a user sees the choose what to sync screen during a registration, we should log a view and the choices submitted.

**Add**
`fxa_reg - cwts_view`
`fxa_reg - cwts_submit`

I added them to the taxonomy doc with proposed properties:
https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4/edit#gid=879531055

I think the main _user property_ that would be different is `cwts_reg` for `fxa_reg - cwts_submit`. I would like to log an array of the engines left enabled when they submitted.

I'm filing this in response to a Slack conversation around confirmation codes between @ryanfeeley and @shane-tomlinson 

CC @irrationalagent -> Make alternative proposal to this taxonomy and event names.

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #938.

Targeted at `train-140` for a patch release. I did a rush job on #1384 and failed to notice the data I was sending to Amplitude included every displayed Sync engine, not just the ones the user had actually selected. This fixes that.

Note there is a quadratic nested loop, where I use `indexOf` inside `filter`. I do this knowingly, because the maximum combined nested iteration count is 36 and we only iterate it once, on submission. It's an imperceptible chunk of time and although I could refactor the auth broker to return a map instead, it didn't seem worth the effort. I'll be happy to oblige if there's disagreement however.

@mozilla/fxa-devs r?

### CODE REVIEW

File: packages/fxa-content-server/app/scripts/views/choose_what_to_sync.js [hunk 1]
```diff
@@ -93,7 +93,10 @@ const View = FormView.extend({
 
     return this.user.setAccount(account)
       .then(account => {
-        this.notifier.trigger('set-sync-engines', offeredSyncEngines);
+        this.notifier.trigger(
+          'set-sync-engines',
+          offeredSyncEngines.filter(e => declinedSyncEngines.indexOf(e) === -1)
```
Comment (philbooth) [inline packages/fxa-content-server/app/scripts/views/choose_what_to_sync.js]: Quadratic nested loop alert!

Comment (vbudhram) [reply packages/fxa-content-server/app/scripts/views/choose_what_to_sync.js]: I think this should be fine, would your front end metrics detect any changes with it?

Comment (philbooth) [reply packages/fxa-content-server/app/scripts/views/choose_what_to_sync.js]: No. We're talking about a couple of milliseconds in the worst case.
