### PR TITLE
fix(auth-server): fix stripe webhook errors

### LINKED ISSUE #7203: Stripe delete webhook returns 404 instead of 200
Stripe sends a webhook on customer delete, this is used by FxA to ensure that if a Stripe customer record is deleted we have removed the Stripe customer id tracking row from the AccountSubscriptions table.

The Stripe webhook logs in production indicate that we are throwing 404's on these, as customers don't exist. My guess is that this is happening during normal customer delete operations, because we delete the FxA account, and then send a delete request to Stripe, so when Stripe then notifies us the customer was deleted, they're already gone.

We should instead respond to this with a 200, so Stripe stops trying to retry, which also flags our API as 'erroring'.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2867)
┆Issue Number: FXA-2867

### PR DESCRIPTION
**Pull request by bbangert**
Because:

* We were rejecting Stripe payloads that exceeded 16Kb, some were as
  large as 22Kb.
* Stripe webhooks that sent emails to customers who deleted their
  account were throwing errors that Stripe keeps retrying.

This commit:

* Updates the maxBytes for the Stripe webhook to accomodate the larger
  payload sizes observed.
* Adds error catching to the email calls in the webhooks to capture and
  report errors that we expect (account deleted), but returns a proper
  200 to Stripe.

Fixes #7203

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

File: packages/fxa-auth-server/lib/payments/stripe.ts [hunk 1]
```diff
@@ -1486,7 +1486,13 @@ export class StripeHelper {
   }
 
   /**
-   * Extract invoice details for billing emails
+   * Extract invoice details for billing emails.
+   *
+   * Note that this function throws an error in the following cases:
+   *   - Stripe customer is deleted.
+   *   - No plan in the invoice.
+   *   - No product attached to the plan.
```
Comment (chenba) [inline packages/fxa-auth-server/lib/payments/stripe.ts:1494]: ??? Does Stripe even allow this?

File: packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts [hunk 2]
```diff
@@ -240,7 +249,19 @@ export class StripeWebhookHandler extends StripeHandler {
...
   ) {
     const sub = event.data.object as Stripe.Subscription;
-    const { uid, email } = await this.sendSubscriptionDeletedEmail(sub);
+    let uid, email;
+    try {
+      ({ uid, email } = await this.sendSubscriptionDeletedEmail(sub));
+    } catch (err) {
+      // FIXME: If the customer was deleted, we don't send an email that their subscription
+      //        was cancelled. This is because the email requires a bunch of details that
+      //        only exist on non-deleted customer. A more robust solution is needed.
```
Comment (chenba) [inline packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts:258]: Is this already captured in a Jira?

**Review by chenba — APPROVED** [review]

File: packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts (hunk 2 above)
Comment (bbangert) [reply packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts:258]: Nope, filing an issue for it.

File: packages/fxa-auth-server/lib/payments/stripe.ts (hunk 1 above)
Comment (bbangert) [reply packages/fxa-auth-server/lib/payments/stripe.ts:1494]: I didn't think they do, but its in the code as a type guard check which means the Stripe API types believe it could occur.

File: packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts (hunk 2 above)
Comment (bbangert) [reply packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts:258]: Filed FXA-3356 for this.
