### PR TITLE
fix(tests): correct error selector in cookies_disabled test

### LINKED ISSUE #7980: Functional test failures - cookies_disabled.js
┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3268)
┆Issue Number: FXA-3268

### PR DESCRIPTION
**Pull request by jaredhirsch**
Fixes #7980.

The error selector has been updated to the new-settings AlertBar, but sometimes we do hit an error on the sign in or sign up pages, as happened here. Might be worth extracting into lib/selectors?

### CODE REVIEW

File: packages/fxa-content-server/tests/functional/lib/helpers.js [hunk 1]
```diff
@@ -2144,7 +2144,7 @@ function testSuccessWasNotShown(selector) {
  */
 function testErrorWasShown(message, selector) {
   selector = selector || selectors.SETTINGS.ERROR;
-  return testElementWasShown(selector);
+  return testElementWasShown(selector, message);
```
Comment (jaredhirsch) [inline packages/fxa-content-server/tests/functional/lib/helpers.js:2147]: Missed a spot last time I was adjusting these error helpers

**Review by vbudhram — APPROVED** [review]
