### PR TITLE
fix(email-first): Redirect to correct settings page after authentication

### LINKED ISSUE #3270: email-first: user is not redirected to correct settings page after signing in
STR

1. In a fresh profile, browse directly to https://accounts.firefox.com/settings/avatar/change
2. Sign in with an existing account
3. We are redirected to /settings instead of /settings/avatar/change

blocks #639

### PR DESCRIPTION
**Pull request by shane-tomlinson**
If a user tried to go to, e.g., /settings/avatar/change
without having a session, they were asked to sign in.
After sign-in, they were redirected back to /settings
rather than /settings/avatar/change because redirectTo
was not correctly propagated. Instead of propagating
the value in the view->view model, rely on the value
stored in the relier.

This also changes the default behavior of an unauthenticdated
user - instead of sending the user to `/signin`,
send the user to `/`

builds on #3281 

fixes #3270

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@mozilla/fxa-devs - r?

File: packages/fxa-content-server/app/scripts/views/index.js [hunk 1]
```diff
@@ -217,7 +217,9 @@ class IndexView extends FormView {
           // ensure it's email is set.
           account.set('email', email);
         }
-        this.navigate(nextEndpoint, { account });
+        this.navigate(nextEndpoint, {
+          account,
+        });
```
Comment (chenba) [inline packages/fxa-content-server/app/scripts/views/index.js]: Prettier works in mysterious ways.
