### PR TITLE
fix(oauth): lower access token lifetimes to six hours plus five minutes

### LINKED ISSUE #5143: Amplitude user properties `sync_active_devices_*` doesn't count Fx iOS anymore and Fenix, and will break when sync moves to oauth
We have several amplitude user properties of the form `sync_active_devices_day`, week and month. These are set only when an `fxa_activity - cert_signed` event is logged, and that event is going away. At that point, we will start relying on the `fxa_activity - access_token*` events to track e.g. DAU and MAU. We should be sure that these sync device count user properties are still set when this happens.

[This is where the device counts are set](https://github.com/mozilla/fxa/blob/045ffadb8e4d8007861641aa96d59e4d069e53c9/packages/fxa-shared/metrics/amplitude.js#L404)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1780)
┆Issue Number: FXA-1780

### PR DESCRIPTION
**Pull request by 6a68**
Fixes #5143.

Our goal is to get sync access token lifetimes down to six hours, so
that the cross-device metrics resolution is the same as it previously
was, when sync used browserid assertions (with a six hour lifetime). By
keeping the TTL just above six hours, we ensure the tokens are backed by
redis, preserving existing validation behavior.

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

### CODE REVIEW

**Comment by 6a68** [comment]
Hmm. Now that I look at this I'm not sure if we'll need to change some sync configuration in-tree to actually accomplish this goal. @rfk thoughts?

R? @jbuck to make sure we aren't going to knock over redis by increasing traffic. I don't know which of our RPs currently use the default JWT expiration when they request access tokens.

**Comment by rfk** [comment]
> Now that I look at this I'm not sure if we'll need to change some sync configuration in-tree to actually accomplish this goal.

I don't think so, any clients that request a non-default ttl are almost certainly doing so in order to get JWTs, and hence requesting something less than 6 hours already.

File: packages/fxa-auth-server/config/index.ts [hunk 1]
```diff
@@ -1062,7 +1062,7 @@ const conf = convict({
       accessToken: {
         doc: 'Access Tokens maximum expiration (can live shorter)',
         format: 'duration',
-        default: '2 weeks',
+        default: '365 minutes',
```
Comment (rfk) [inline packages/fxa-auth-server/config/index.ts:1065]: nit: it may be worth a brief inline comment to explain this weird number, lest our future selves mistake it for a typo :-)

**Review by rfk — APPROVED** [review]

File: packages/fxa-auth-server/config/index.ts (hunk 1 above)
Comment (6a68) [reply packages/fxa-auth-server/config/index.ts:1075]: @rfk added perhaps excessively verbose comment here 🤷 feedback welcome

Comment (rfk) [reply packages/fxa-auth-server/config/index.ts:1075]: Haha, you did not muck around with this one, thanks!

**Comment by 6a68** [comment]
I'm going to go ahead and land this. I'll make a note of the change in the deploy doc for the next release.
