### PR TITLE
fix(tests): get sign_in_blocked tests passing

### LINKED ISSUE #7982: Functional test failures - sign_in_blocked.js
┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3266)
┆Issue Number: FXA-3266

### PR DESCRIPTION
**Pull request by jaredhirsch**
* Extract duplicated secondary email setup code into a helper

* Extract duplicated sign out code into a helper

Fixes #7982.

### CODE REVIEW

File: packages/fxa-content-server/tests/functional/force_auth.js [hunk 1]
```diff
@@ -15,6 +15,7 @@ const {
   createUser,
   fillOutForceAuth,
   openForceAuth,
+  signOut,
```
Comment (vbudhram) [inline packages/fxa-content-server/tests/functional/force_auth.js:18]: Nice 👍🏽

File: packages/fxa-content-server/tests/functional/settings_v2/navigation.js [hunk 2]
```diff
@@ -105,16 +105,6 @@ describe('navigation', () => {
...
-      selectors.SETTINGS_V2.AVATAR_DROP_DOWN_MENU.DISPLAY_NAME_LABEL,
-      remote
-    );
-    await click(
-      selectors.SETTINGS_V2.AVATAR_DROP_DOWN_MENU.SIGNOUT_BUTTON,
-      selectors.ENTER_EMAIL.HEADER,
-      remote
-    );
-    await testElementExists(selectors.ENTER_EMAIL.HEADER, remote);
+    await signOut(remote);
```
Comment (vbudhram) [inline packages/fxa-content-server/tests/functional/settings_v2/navigation.js:108]: Do you find the await syntax easier to follow than chained promises? At some point we can convert everything to use the same pattern.

**Review by vbudhram — APPROVED** [review]

File: packages/fxa-content-server/tests/functional/settings_v2/navigation.js (hunk 2 above)
Comment (jaredhirsch) [reply packages/fxa-content-server/tests/functional/settings_v2/navigation.js:108]: Great question! I honestly haven't thought about it much, but it would be nice to standardize on just one approach.
