### PR TITLE
fix(payments): include time fields in amplitude events

### LINKED ISSUE #3050: Payments metrics missing `time` key
Payments data on stage is not showing up in amplitude because of a missing `time` key.

This field is required because amplitude uses it to construct its time series.

### PR DESCRIPTION
**Pull request by 6a68**
Note: opening as a draft because this still needs tests, but I want to make sure the overall approach seems correct.

Commit message continues:
-----

Specifically, include the `perfStartTime`, `startTime`, and `flushTime`
in each amplitude event emitted by the front-end.

More details:

The content-server amplitude events are also flow events, meaning
the `perfStartTime` and other times needed to reconstruct the event time
on the server are already available on the event object. The arithmetic
used to calculate `event.time` was copied over to the payments server
post-metrics route handler code without verifying that the needed data
was available on the amplitude events emitted by the front-end.

Unlike content server, the payments server amplitude events are
generated by a redux middleware that observes certain actions dispatched
while the user interacts with the payments pages, which is separate from
how payments flow events are generated and processed. This means that the
necessary time values need to be explicitly added to each amplitude event
before the event is sent down to the server.

I verified this patch fixed the issue by attaching the node debugger to
a local payments server process, but you could also look in the payments
server logs for an amplitude event logged with a `time` property. One
such event (the engage event) is emitted as soon as a character is typed
into the subscription form.

Hopefully, this really fixes #3050.

### CODE REVIEW

File: packages/fxa-payments-server/src/store/amplitude-middleware.ts [hunk 1]
```diff
@@ -100,79 +109,95 @@ export const AmplitudeMiddleware: Middleware = (
...
-          ...getFailureReasonFromAction(action),
-        });
+        logAmplitudeEvent(
+          eventGroupNames.updatePayment,
+          eventTypeNames.fail,
+          config.perfStartTime,
+          {
+            ...getPlanPropsFromAction(action),
+            ...getFailureReasonFromAction(action),
+          }
```
Comment (6a68) [inline packages/fxa-payments-server/src/store/amplitude-middleware.ts]: idk why prettier does this formatting sometimes but not always 🤷‍♂️

**Comment by chenba** [comment]
That make sense.  Thanks @6a68 for digging into it.

Looking at this, it seems kinda silly that we re-calculate the time of the event given that we have the value at the time of the event [0]!  We send an `offset` because that's what content server did.  But what would break if we send the event time in addition or instead?  (I'm mostly mumbling to myself here... we don't need to change the patch or anything.)

[0] which was what I think the original patch was expecting?

**Comment by 6a68** [comment]
Really good point about the use of `offset` 🤔 ...I hope we can make time to simplify all this metrics code soon

**Comment by chenba** [comment]
```
fxa-payments-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_subscribe_cancel - complete","time":1573160831540,"device_id":"2bd2fc04efa340e8955cdf9cb30a7b88","session_id":"1573160811376","app_version":"149.4","os_name":"Windows","os_version":"10","event_properties":{"plan_id":"123doneProMonthly","product_id":"123doneProProduct"},"user_properties":{"flow_id":"2cdacfc6d57f7092e23f87fcdbf286045f96eb446732294d289560d72bb65a39","ua_browser":"Firefox","ua_version":"72.0"}}
```
Verified locally.
