### PR TITLE
fix(settings): add confirm recovery code modal

### LINKED ISSUE #9530: [TOTP] "Confirm recovery code" modal is not displayed when generating new codes (replace)
Prerequisites:

* 2FA is enabled

### Steps to reproduce
1. From 2FA section tap on "Generate recovery codes". 
1. Save the codes and tap on "Continue".

### Expected result
"Confirm recovery code" modal is displayed.

### Actual result
The modal is dismissed. 2FA section is displayed and 2FA is enabled. 

### Environment
* Mobile, Desktop
* Train 154 - stage server

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-905)

### PR DESCRIPTION
**Pull request by dschom**
## Because

- When generating new recovery codes, there was no confirmation step, which might make it easy for a user to overlook the fact they should download / record their recovery codes.

## This pull request

- Introduces the same dialog, which existed in the initial 2FA flow, that prompted a user for at least one recovery code as a way to validate users had recorded them
- Introduces the same dialog, which existed in the initial 2FA flow, that prompted a user for at least one recovery code as a way to validate users had recorded them
- Introduces back end support for creating and updating recovery codes as a two step process
- Shifts recovery code generation to client, relocating crypto/random.ts to fxa-shared, so it's accessible
- Adds validation for recovery codes being updated
- Exposes recovery code length / count settings to client
- Adds section about running play write tests to read me

## Issue that this pull request solves

Closes: #9530

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

**Comment by dschom** [comment]
@dannycoates In the related issue (#9530), you mentioned there may be back end changes needed. After working on the issue a bit, I do see your point. I am not sure, however, if the back end changes should be a separate request or not. This PR includes the recovery code confirmation dialog. This encourages users to record their recovery codes, so in my opinion, it is still a step forward. Let me know what you think. If you think the back end changes are necessary, I can build on top of this draft.

File: packages/fxa-auth-server/lib/routes/recovery-codes.js [hunk 1]
```diff
@@ -65,6 +65,99 @@ module.exports = (log, db, config, customs, mailer) => {
...
+        validate: {
+          payload: {
+            recoveryCodes: isA.array().items(isA.string()),
+          },
+        },
+        response: {
+          schema: {
+            success: isA.boolean(),
+          }
+        }
```
Comment (dannycoates) [inline packages/fxa-auth-server/lib/routes/recovery-codes.js:119]: I thought about this a bit more...

I think we're actually ok with accepting values from the client as long as we can validate them since we require a verified session, the codes are random and not connected to any other data, and we send a confirmation email. A round trip with a signed JWT is overkill for this.

Our validation should be more thorough than what's here so far. We should ensure they are the correct length and valid base32, no duplicates.

And since we're allowing client values we don't really need a server endpoint to generate them. We can use https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues on the client-side

File: packages/fxa-content-server/tests/functional/settings/two_step_auth.js [hunk 2]
```diff
@@ -169,7 +170,7 @@ registerSuite('TOTP', {
         .then(testElementExists(selectors.ENTER_EMAIL.HEADER));
     },
 
-    'can navigate directly to recovery codes': function () {
+    'can change recovery codes': function () {
```
Comment (dannycoates) [inline packages/fxa-content-server/tests/functional/settings/two_step_auth.js:173]: congratulations figuring out how to write one of these functional tests 😆

File: packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.test.tsx [hunk 3]
```diff
@@ -56,3 +75,42 @@ it('displays an error when fails to fetch new recovery codes', async () => {
   });
   expect(context.alertBarInfo?.error).toBeCalledTimes(1);
 });
+
+it('forces users to validate recovery code', async () => {
+  await renderPage2faReplaceRecoveryCodes();
+
+  await act(async () => {
```
Comment (dannycoates) [inline packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.test.tsx:82]: @jodyheavener will have <strike>opinions</strike> suggestions about this 😉

**Review by dannycoates — CHANGES_REQUESTED** [review]
This is looking great! I like how you implemented the server side really succinctly

File: packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.test.tsx [hunk 4]
```diff
@@ -4,42 +4,61 @@
...
+  generateRecoveryCodes: jest.fn().mockResolvedValue(recoveryCodes),
+  updateRecoveryCodes: jest.fn().mockResolvedValue({ success: true }),
 } as unknown as Account;
 
+const config = {
+  recoveryCodes: {
+    count: 1,
+    length: 10,
+  },
+} as unknown as Config;
```
Comment (jodyheavener) [inline packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.test.tsx:32]: I don't think this needs to be `as unknown`

File: packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.test.tsx (hunk 3 above)
Comment (jodyheavener) [reply packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.test.tsx:82]: yeah basically you shouldn't need to use `act` 99% of the time - [here's a presentation](https://drive.google.com/file/d/1-M_Dkh1gfJZNTJJYy_CEkDR9UkIp-Dak/view?usp=sharing) explaining why, as well as some other nifty tips

File: packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.test.tsx [hunk 5]
```diff
@@ -56,3 +75,42 @@ it('displays an error when fails to fetch new recovery codes', async () => {
   });
   expect(context.alertBarInfo?.error).toBeCalledTimes(1);
 });
+
+it('forces users to validate recovery code', async () => {
+  await renderPage2faReplaceRecoveryCodes();
+
+  await act(async () => {
+    await fireEvent.click(screen.getByTestId('ack-recovery-code'));
```
Comment (jodyheavener) [inline packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.test.tsx:83]: also `fireEvent` isn't async, so you don't need `await` on them

File: packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.test.tsx [hunk 6]
```diff
@@ -56,3 +75,42 @@ it('displays an error when fails to fetch new recovery codes', async () => {
...
+  });
+  await act(async () => {
+    await fireEvent.click(screen.getByTestId('submit-recovery-code'));
+  });
+
+  expect(mockNavigate).toHaveBeenCalledWith(
+    HomePath + '#two-step-authentication',
+    { replace: true }
+  );
+});
```
Comment (jodyheavener) [inline packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.test.tsx:116]: `act`-less version:

```tsx
it('allows user to finish', async () => {
  await renderPage2faReplaceRecoveryCodes();

  fireEvent.click(screen.getByTestId('ack-recovery-code'));
  await typeByTestIdFn('recovery-code-input-field')(recoveryCodes[0]);
  fireEvent.click(screen.getByTestId('submit-recovery-code'));

  await waitFor(() =>
    expect(mockNavigate).toHaveBeenCalledWith(
      HomePath + '#two-step-authentication',
      { replace: true }
    )
  );
});
```

File: packages/fxa-settings/src/lib/random.test.ts [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+        } else {
+          map[r]++;
+        }
+
+        assert.equal(r.length, 10);
+        assert.isTrue(regex.test(r));
+      }
+
+      assert.isFalse(Object.values(map).some((x) => x > 1));
+    }
```
Comment (dannycoates) [inline packages/fxa-settings/src/lib/random.test.ts:120]: I think we can trust the rng at this point. We'd need a lot more than 1000 iterations to increase our confidence if we were in doubt.

If you want to ensure `randomValue` is doing the right thing with those random bytes it'd be good to start by mocking `getRandomValues` with a known set of bytes (a test vector) and ensure you get the encoded string(s) you expect.

File: packages/fxa-auth-server/lib/routes/recovery-codes.js [hunk 8]
```diff
@@ -6,13 +6,21 @@
 
 const errors = require('../error');
 const isA = require('@hapi/joi');
-const BASE_36 = require('./validators').BASE_36;
+const validators = require('./validators');
+
+const RECOVERY_CODE_SANE_MAX_COUNT = 20;
```
Comment (dannycoates) [inline packages/fxa-auth-server/lib/routes/recovery-codes.js:11]: I think we can just use `RECOVERY_CODE_COUNT` from below

File: packages/fxa-content-server/server/lib/configuration.js [hunk 9]
```diff
@@ -467,6 +467,20 @@ const conf = (module.exports = convict({
     doc: 'The publically visible URL of the deployment',
     env: 'PUBLIC_URL',
   },
+  recovery_codes: {
+    count: {
+      default: 3,
```
Comment (dannycoates) [inline packages/fxa-content-server/server/lib/configuration.js:472]: let's default this to the production value of 8 and set it in `server/config/local.json` as 3

**Review by dannycoates — APPROVED** [review]
This looks good @dschom 🎉 ... just a couple tiny things

**Comment by dannycoates** [comment]
was this closed on purpose?

**Comment by dschom** [comment]
It was not closed intentionally! I have corrected the problem. I _think_ this was the result of a botched push. I re-based off main and effectively undid my changes by accident :disappointed:. I think that with zero file changes, github then marked the PR as closed.
