### PR TITLE
fix(auth): stop reporting errors on legit credit notes

### LINKED ISSUE #9323: We should not report sentry errors for non-paypal credit notes.
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11528137/?referrer=github_plugin

    Error: Credit note issued for account balance: cn_1J08XjJNcmPzuWtR4JdJljia
      File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.js", line 131, in StripeWebhookHandler.handleCreditNoteEvent
        sentry_1.reportSentryError(new Error(`Credit note issued for account balance: ${creditNote.id}`), request);
      ?, in runMicrotasks
      File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.js", line 59, in async StripeWebhookHandler.handleWebhookEvent
        await this.handleCreditNoteEvent(request, event);
    ...
    (4 additional frame(s) were not displayed)We should ignore invoices with charge automatically, and if its send_invoice and not out_of_band, then we report it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3619)

### PR DESCRIPTION
**Pull request by bbangert**
Because:

* We are incorrectly reporting Sentry errors when refunding users
  that paid via Stripe on credit notes.

This commit:

* Only reports via Sentry if a Stripe paying user was credited out of
  band or on their account balance.

Closes #9323

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

File: packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts [hunk 1]
```diff
@@ -147,17 +147,23 @@ export class StripeWebhookHandler extends StripeHandler {
...
-    ) {
-      reportSentryError(
-        new Error(`Credit note issued for account balance: ${creditNote.id}`),
-        request
-      );
+    if (invoice.collection_method === 'charge_automatically') {
+      // This is a Stripe charge, report if needed and return as Stripe handles
+      // refunding the customer.
+      if (
+        creditNote.customer_balance_transaction ||
```
Comment (biancadanforth) [inline packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts:154]: Wouldn't we still want to check for an account balance for PayPal customers and report an error? That would mean it was issued incorrectly, right?

Admittedly, I guess we weren't checking for that here originally for either Stripe or PayPal.

**Review by biancadanforth — APPROVED** [review]
Thanks Ben; LGTM. Just had a follow-up question re: account balances and PayPal customers.

File: packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts (hunk 1 above)
Comment (bbangert) [reply packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts:154]: This only exists if the credit note adjusts the account balance, which only happens if the user is being credited to their balance which we currently don't want.

Comment (biancadanforth) [reply packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts:154]: Hmm yeah I understand that part, but we aren't checking if the credit note adjusts the account balance for PayPal customers with this logic -- only for Stripe customers. Shouldn't we also check this for PayPal customers?

Comment (bbangert) [reply packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts:154]: We will want that in a future PR to allow partial paypal refunds. There's a if block farther down here that ensures the out_of_band amount perfectly matches the invoice amount. If there was a account balance change for a PayPal user, then that check below will fail and it will error.
