### PR TITLE
fix(auth): make unknown properties valid for support-panel route

### LINKED ISSUE #12055: [subplat][support-panel] Support Panel throws an error if the customer is a Google IAP subscriber
See [https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/7843129/events/92085018/](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/7843129/events/92085018/)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4663)

### PR DESCRIPTION
**Pull request by biancadanforth**
Because:

* The fxa-auth-server was returning 500s for the support-panel route due to a response validation error.

This commit:

* Allows unknown properties on the web and Google Play subscription objects returned in the response.
* Adds the missing 'price_id' property as an optional property for Play subscriptions returned by the endpoint.

Closes #12055

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

File: packages/fxa-auth-server/lib/routes/validators.js [hunk 1]
```diff
@@ -389,27 +389,32 @@ module.exports.subscriptionsSubscriptionValidator = isA.object({
...
+    auto_renewing: isA.bool().required(),
+    cancel_reason: isA.number().optional(),
+    expiry_time_millis: isA.number().required(),
+    package_name: isA.string().optional(),
+    price_id: isA.string().optional(),
+    product_id: isA.string().optional(),
+    product_name: isA.string().required(),
+    sku: isA.string().optional(),
+  })
+  .unknown(true);
```
Comment (bbangert) [inline packages/fxa-auth-server/lib/routes/validators.js:417]: Why the unknown?

**Review by bbangert — APPROVED** [review]
LGTM, just curious about the reason for allowing unknown keys.

File: packages/fxa-auth-server/lib/routes/validators.js (hunk 1 above)
Comment (biancadanforth) [reply packages/fxa-auth-server/lib/routes/validators.js:417]: Well originally I just added the `price_id` property and that fixed it, however because it's an optional property, the validator test passes regardless of that change. I was trying to find a way to prevent this type of error from ever occurring again.

I noticed in the support panel that only the required fields are displayed and nothing is done with the optional fields (at least for Google IAP subscriptions). So I didn't see the harm in allowing unknown properties.

Also my understanding is that the admin panel work to list subscriptions and create a Support LDAP group will eventually lead us to deprecate and sunset the Support Panel entirely, so preventing our team from spending time fixing bugs in the mean time seems like a good call.

I'm open to just adding the `price_id` property and removing the unknowns if you think that's better?
