### PR TITLE
fix(pairing): make sure not to use unverified sessions for pairing

### LINKED ISSUE #1130: [fxa-content-server] The /pair may still fail with 'Unverified session'
image

Vesta has reported in Slack that she got a `Unverified session` when going to `/pair` on 

```
{
  "commit": "39875bc8cc974987cbccf8bd543a6220ccad8938",
  "version": "1.136.5",
  "l10n": "cba64f5829a9fa89d3d329b904725c5a6b383ef9",
  "tosPp": "e25ae12c4465163f2021d52899d7ed5947d2bcc0",
  "source": "https://github.com/mozilla/fxa"
}
```

@shane-tomlinson @rfk Should we be worried that this conditional is not enough https://github.com/mozilla/fxa/blob/dcf8db2529513409bfa767840ef56b281f9f1b18/packages/fxa-content-server/app/scripts/views/pair/index.js#L37  ?

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #1130 

@shane-tomlinson r?

See the problem described in https://github.com/mozilla/fxa/issues/1130#issuecomment-493278186

### CODE REVIEW

**Comment by vladikoff** [comment]
Filed against train-137

File: packages/fxa-content-server/app/scripts/models/user.js [hunk 1]
```diff
@@ -713,17 +713,17 @@ var User = Backbone.Model.extend({
    * Should the model be initialized using browser data?
    *
    * @param {Object} service service being signed into.
-   * @param {Boolean} isDevicePairingAsAuthority
+   * @param {Boolean} isPairing device is trying to pair
    * @returns {Boolean}
    */
-  shouldSetSignedInAccountFromBrowser (service, isDevicePairingAsAuthority) {
-    // If service=sync or the device is pairing as the authority,
+  shouldSetSignedInAccountFromBrowser (service, isPairing) {
```
Comment (vbudhram) [inline packages/fxa-content-server/app/scripts/models/user.js]: This makes sense to me. To have access to the start pairing button, the browser should have gone through at least an email verification. If the session has been email verified then it would be able to call the `checkTotpStatus` endpoint and see if the account has TOTP.
