### PR TITLE
fix(auth): check paymentAttempts before returning a funding source error

### LINKED ISSUE #11992: [Subplat]Manage subscriptions page displays an error when upgrading via PayPal from monthly to yearly plan
*FxA version:*

* 1.226.0;

*Prerequisites:*

* Have a FxA account that has an upgrade made from the monthly plan for MDN to the yearly plan;

*Steps to reproduce:*

* Go to 

[+https://accounts.stage.mozaws.net/signin+|https://accounts.stage.mozaws.net/signin] and sign in with the account from prerequisites;

* Go to Paid subscriptions page;

*Expected result:*

* The page is displayed without any issues;

*Actual result:*

* There’s an error message displayed regarding invalid payment information;

*Notes:*

* See the attached screenshots;
* This is also reproducible for Mozilla VPN product upgrade from monthly to yearly plan;

* This is a major issue because the user may think that there’s something wrong with their payment information;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4637)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/20789">image_2022_02_22T09_31_04_152Z.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/20782">paypal.png</a>

### PR DESCRIPTION
**Pull request by biancadanforth**
Because: 
* #10857 changed how we process recurring PayPal payments to use the paypal-processor rather than the invoice.finalized Stripe webhook.
* Our mozilla-subscriptions/customer/billing-and-subscriptions endpoint was wrongly returning a PayPal "funding_source" error to the front-end, because the 'getBillingDetailsAndSubscriptions' helper was only checking if an invoice was open -- not whether we've actually tried to pay it.
    
This commit:
* Checks the 'paymentAttempts' metadata on any open invoices for active subscriptions before returning a PayPal funding source error to the client.
    
Closes #11992

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

## Other information (Optional)

There's a second commit here related to a yarn.lock change that came up after I `yarn install`ed. Another miss with dependabot?

### CODE REVIEW

File: packages/fxa-auth-server/lib/payments/stripe.ts [hunk 1]
```diff
@@ -1980,9 +1991,17 @@ export class StripeHelper {
...
           PAYPAL_PAYMENT_ERROR_MISSING_AGREEMENT;
-      } else if (await this.hasOpenInvoice(customer)) {
-        billingDetails.paypal_payment_error =
-          PAYPAL_PAYMENT_ERROR_FUNDING_SOURCE;
+      } else {
+        const invoices = await this.getLatestInvoicesForActiveSubscriptions(
+          customer
+        );
+        if (
+          this.hasOpenInvoice(invoices) &&
```
Comment (chenba) [inline packages/fxa-auth-server/lib/payments/stripe.ts:1999]: We don't need this half of the predicate.  `some` will return false if the array is empty.

**Review by chenba — APPROVED** [review]
👍

File: packages/fxa-auth-server/lib/payments/stripe.ts (hunk 1 above)
Comment (biancadanforth) [reply packages/fxa-auth-server/lib/payments/stripe.ts:1999]: If I remove this predicate, the logic will incorrectly return false if there are paid invoices on any active subscriptions, since paymentAttempts for a paid PayPal invoice would also be > 0 (just tried it locally).

@chenba am I misunderstanding you?

Comment (chenba) [reply packages/fxa-auth-server/lib/payments/stripe.ts:1999]: Oh sorry, I was focusing too much on the addition (green) part of the diff.  You're correct, we need this because of the 'open' status filtering part.  🤦

Comment (biancadanforth) [reply packages/fxa-auth-server/lib/payments/stripe.ts:1999]: No worries.

Actually after looking at this logic more closely, I think I need to ensure that the _same_ invoice is both open _and_ has paymentAttempts > 0. Otherwise it's possible that the user has e.g. two active subscriptions, one with a paid invoice (and 1 payment attempt) and the other upgraded subscription with an open invoice and 0 payment attempts. Right now they would incorrectly get this error still (though this is a different scenario than the bug filed by QA).

**Review by chenba — APPROVED** [review]
That was a good catch.  💯
