### PR TITLE
fix(test): Fix the settings/avatar tests

### LINKED ISSUE #3099: latest test failures: settings/avatar - attempt to use webcam for avatar, upload a profile image
Seen on teamcity in this run: https://tc-test.dev.lcip.org/viewLog.html?buildId=60023&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests

Reproducible locally by running `npm run test-latest -- --grep="settings/avatar"

> Screenshot saved at: https://screencap.co.uk/images/38879bdd1e88602698199a4ab67c231a631a0bf1.png
× firefox on mac 18.7.0 - settings/avatar - attempt to use webcam for avatar (8.61s)
    Error: NoSuchBrowserNotification
      at Command.<anonymous> @ tests/functional/lib/helpers.js:1830:41
      at Command.<anonymous> @ tests/functional/lib/helpers.js:1828:8
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:75:18
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Command.<anonymous> @ tests/functional/avatar.js:49:22
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Test.attempt to use webcam for avatar [as test] @ tests/functional/avatar.js:121:12
      @ src/lib/Test.ts:263:51
>
> ✓ firefox on mac 18.7.0 - settings/avatar - attempt to use webcam for avatar, then cancel (5.299s)
Screenshot saved at: https://screencap.co.uk/images/51aa76b281f965385bd1a711bf2c77f690f1cfe3.png
× firefox on mac 18.7.0 - settings/avatar - upload a profile image (8.301s)
    Error: NoSuchBrowserNotification
      at Command.<anonymous> @ tests/functional/lib/helpers.js:1830:41
      at Command.<anonymous> @ tests/functional/lib/helpers.js:1828:8
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:75:18
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Command.<anonymous> @ tests/functional/avatar.js:49:22
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Test.upload a profile image [as test] @ tests/functional/avatar.js:162:12
      @ src/lib/Test.ts:263:51

blocks #2877

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Move the `testIsBrowserNotified` checks after the avatar is loaded
to give a bit more time.

Also updated to use the selectors module, and email-first instead
of the legacy /signin page.

fixes #3099

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@mozilla/fxa-devs - r?

File: packages/fxa-content-server/tests/functional/avatar.js [hunk 1]
```diff
@@ -23,7 +23,7 @@ const SETTINGS_URL = config.fxaContentRoot + 'settings';
 const SETTINGS_URL_IOS10 = `${SETTINGS_URL}?forceUA='${encodeURIComponent(
   ios10UserAgent
 )}`;
-const SIGNIN_URL = config.fxaContentRoot + 'signin';
+const ENTER_EMAIL_URL = config.fxaContentRoot + '?action=email';
```
Comment (vladikoff) [inline packages/fxa-content-server/tests/functional/avatar.js]: 👍
