### PR TITLE
fix(test): Fix the broken delete_account test

### LINKED ISSUE #3101: latest test failure: delete_account, sign in, cancel delete account
Seen here: https://tc-test.dev.lcip.org/viewLog.html?buildId=60023&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests as well as locally

STR
1. `npm run test-latest -- --grep="delete_account - sign in, cancel delete account"`

> × firefox on mac 18.7.0 - delete_account - sign in, cancel delete account (4.706s)
    StaleElementReference: [POST http://localhost:4444/wd/hub/session/c581c54b-a542-724a-ab0e-c3ebd2ea632e/element/a8f2e8a2-2d2c-034d-8d6c-7b0b7643c60a/click / {}] The element reference of <button class="settings-button secondary-button cancel"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
    For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'stomlinson-30887', ip: '192.168.1.229', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '9.0.1'
    Driver info: driver.version: unknown
      at Test.sign in, cancel delete account [as test] @ tests/functional/delete_account.js:73:12
      @ src/lib/Test.ts:263:51

blocks #2877

### PR DESCRIPTION
**Pull request by shane-tomlinson**
After clicking the "cancel" button we were checking for the existence
of the '#settings' element, which could have gone stale due to a re-render.

Instead, ensure the delete panel details become hidden.

fixes #3101

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@mozilla/fxa-devs - r?

File: packages/fxa-content-server/tests/functional/delete_account.js [hunk 1]
```diff
@@ -7,75 +7,73 @@
...
-          .end()
+          .then(
+            click(
+              selectors.SETTINGS_DELETE_ACCOUNT.MENU_BUTTON,
+              selectors.SETTINGS_DELETE_ACCOUNT.DETAILS
+            )
+          )
+
+          .then(click(selectors.SETTINGS_DELETE_ACCOUNT.CANCEL))
+          .then(pollUntilHiddenByQSA(selectors.SETTINGS_DELETE_ACCOUNT.DETAILS))
```
Comment (vladikoff) [inline packages/fxa-content-server/tests/functional/delete_account.js]: 👍
