### PR TITLE
fix(signin): allow email first users w/ invalid sessions to sign in

### LINKED ISSUE #999: Login Error on Monitor
Conditions:
- Nightly 68.0a1 (2019-04-29) (64-bit)
- Mac
- Signed in to sync in the browser

Steps to reproduce:
- Go to monitor.firefox.com
- Click Sign in top right of page
- On account.firefox.com (your email should already be displayed), click Sign In

Result:
- Unexpected Error (See screenshot)

Expected:
- Successful login

Console log:

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Users that sign into Sync in one browser and disconnect the session
in another browser were unable to sign in using the email-first flow
because the sessionToken was removed from the account but the
sessionTokenContext was not. The user wasn't asked for their
password and had no way to remedy the situation. This ensures
that when we remove the sessionToken, we also remove the
sessionTokenContext and any accessTokens.

This also provides a remedy for users already in this state. If
we find that an account has a sessionTokenContext but no
sessionToken, then remove the sessionTokenContext so
they can sign in.

Opened against train-135.

fixes #999

@vladikoff, @philbooth, @vbudhram - r?

### CODE REVIEW

File: packages/fxa-content-server/app/scripts/models/account.js [hunk 1]
```diff
@@ -135,11 +153,6 @@ const Account = Backbone.Model.extend({
     // upgrade the credentials with verified state
     return this.sessionStatus()
       .catch((err) => {
-        // if invalid token then invalidate session
```
Comment (shane-tomlinson) [inline packages/fxa-content-server/app/scripts/models/account.js]: I removed this because it's guaranteed to happen in `sessionStatus` now.
