### PR TITLE
fix(experiment): Fix signup code experiment so it reports to amplitude

### LINKED ISSUE #2458: Signup code metrics are not being reported in amplitude
We should have been receiving metrics for the Boomerang signup code experiment in Amplitude, but we are not. Forcing the experiment will give you the expected flow, however we do not report metrics when the flow is force.

Tracking bug to investigate why no metrics being reported.

cc @irrationalagent @davismtl

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #2458 

After a little digging, I found that the experiment was not included in the manual experiments. Once it was added there the experiment data was logged. I also updated the experiment docs to mention this.

Targeting as a point release on train 145

Screen Shot 2019-09-10 at 4 21 03 PM

### CODE REVIEW

File: packages/fxa-auth-server/lib/metrics/amplitude.js [hunk 1]
```diff
@@ -38,6 +38,7 @@ const EMAIL_TYPES = {
   recoveryEmail: 'reset_password',
   unblockCode: 'unblock',
   verifyEmail: 'registration',
+  verifyShortCodeEmail: 'registration',
```
Comment (vbudhram) [inline packages/fxa-auth-server/lib/metrics/amplitude.js]: This was needed for amplitude to log the email metrics, it was in the documentation I just missed it 🤦🏽‍♂️

Comment (rfk) [reply packages/fxa-auth-server/lib/metrics/amplitude.js]: I wonder if we can prevent this in future by having a check when the auth-server starts up, that checks whether all the known emails have a corresponding entry in this list.

Comment (vbudhram) [reply packages/fxa-auth-server/lib/metrics/amplitude.js]: I agree, having a check would have helped catch this 👍🏽, we could probably/add extend this in this [issue](https://github.com/mozilla/fxa/issues/511).
