### PR TITLE
fix(marketing): Add back the ability for account model to set `needsOptedInToMarketingEmail`

### LINKED ISSUE #5135: 500 error: "needsOptedInToMarketingEmail cannot be set on an Account"
Hi, I’m getting a 500 error when accessing accounts.firefox.com while being connected to my account in Firefox Nightly

image

Here’s the console output: 
```
18:41:54,327 Error: "needsOptedInToMarketingEmail cannot be set on an Account"
    set marketing_snippet.js:212
    Underscore 2
    Backbone 2
    initAccount app.js:14
    n app.js:14
    collect Underscore
    getChooserAccount app.js:14
    suggestedAccount sign_in_password.js:25
    value complete_reset_password.js:139
    value complete_reset_password.js:75
    mixin/</i[n]/< Backbone
    Underscore 2
    n Backbone
    render base.js:296
    promise callback*render/< base.js:289
    promise callback*render base.js:268
    showView support.js:276
    promise callback*showView support.js:258
    i notifier-mixin.js:70
    Backbone 4
    showView app.js:14
    r app.js:14
    promise callback*$r/< app.js:14
    Backbone 3
    any Underscore
    Backbone 2
    allResourcesReady app.js:14
    startApp app.js:14
    promise callback*startApp app.js:14
    <anonymous> app.js:14
    promise callback* app.js:14
    Webpack 4
        s
        n
        <anonymous>
        <anonymous>
logger.js:72:35
```

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1775)
┆Issue Number: FXA-1775

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #5135 

I believe there are still some old resume tokens that use this and it might require an additional train before it can be fully removed. This PR allows setting the property meanwhile (it still isn't used anywhere).

### CODE REVIEW

File: packages/fxa-content-server/app/scripts/models/account.js [hunk 1]
```diff
@@ -62,6 +62,8 @@ const DEFAULTS = _.extend(
     keyFetchToken: undefined,
     newsletters: undefined,
     offeredSyncEngines: undefined,
+    // `needsOptedInToMarketingEmail` is kept around to load from old ResumeTokens.
```
Comment (vladikoff) [inline packages/fxa-content-server/app/scripts/models/account.js:65]: maybe add a note when this can be removed, so we can clean it up later

**Comment by l-hedgehog** [comment]
I've seen `needsOptedInToMarketingEmail` stored in my localStorage, as part of some old test accounts:

```
>> Object.values(JSON.parse(localStorage.getItem("__fxa_storage.accounts") || "{}")).filter(account => account.hasOwnProperty("needsOptedInToMarketingEmail"))
<< Array(3) [ {…}, {…}, {…} ]
```

Is it necessary to explicitly remove them?
