### PR TITLE
fix(apple): Generate JWT for client secret on each request

### LINKED ISSUE #12391: Generate Apple auth secrets on each request to auth
Per Apple documentation, we should generate the secrets needed to do an auth on each request. Currently, the manually generated secrets will expire in 6 months.

Ref https://bannister.me/blog/generating-a-client-secret-for-sign-in-with-apple-on-each-request

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4817)

### PR DESCRIPTION
**Pull request by xlisachan**
Because:

* Apple only requires the generated token to be updated every six months

This commit:

* Generates the JWT for the client secret on each request as a better approach

Closes #12391

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

File: packages/fxa-auth-server/config/index.ts [hunk 1]
```diff
@@ -150,13 +150,37 @@ const conf = convict({
...
+      format: String,
+      doc: 'Apple auth private key',
+    },
+    teamId: {
+      default: '',
+      env: 'APPLE_AUTH_TEAM_ID',
+      format: String,
+      doc: 'Apple auth team id',
+    },
+    appleEndpoint: {
```
Comment (vbudhram) [inline packages/fxa-auth-server/config/index.ts:178]: This is actually the openid spec `aud`.

From https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens:

> The audience registered claim identifies the intended recipient of the client secret. Since the client secret is sent to the validation server, use https://appleid.apple.com.

 I think we can put it as a constant in file and not as a config.

**Review by vbudhram — COMMENTED** [review]
@xlisachan Thank you! Code looks right and I will try to run it locally with my developer account later and see if it works.

File: packages/fxa-auth-server/lib/routes/linked-accounts.ts [hunk 2]
```diff
@@ -44,6 +45,29 @@ export class LinkedAccountHandler {
     }
   }
 
+  // As generated tokens expire after 6 months (180 days) per Apple documentation,
+  // generate JWT for client secret on each request instead
+  async generateAppleToken() {
```
Comment (vbudhram) [inline packages/fxa-auth-server/lib/routes/linked-accounts.ts:50]: This could be named `generateAppleClientSecret` to be more clear.

File: packages/fxa-auth-server/lib/routes/linked-accounts.ts [hunk 3]
```diff
@@ -44,6 +45,29 @@ export class LinkedAccountHandler {
...
+    const { clientId, keyId, privateKey, teamId } = this.config.appleAuthConfig;
+
+    if (!privateKey || !clientId || !keyId || !teamId) {
```
Comment (vbudhram) [inline packages/fxa-auth-server/lib/routes/linked-accounts.ts:53]: I think we can pass these values into the function so that we wouldn't need to reference the config file and do config check earlier.

File: packages/fxa-auth-server/lib/routes/linked-accounts.ts [hunk 4]
```diff
@@ -44,6 +45,29 @@ export class LinkedAccountHandler {
...
+    }
+    
+    const ecPrivateKey = await jose.importPKCS8(privateKey, 'ES256');
+
+    const jwt = await new jose.SignJWT({})
+      .setProtectedHeader({ alg: 'ES256', kid: keyId })
+      .setIssuedAt()
+      .setIssuer(teamId)
+      .setAudience(appleAud)
+      .setExpirationTime('2h')
```
Comment (vbudhram) [inline packages/fxa-auth-server/lib/routes/linked-accounts.ts:64]: Since is this generated on a per request basis we could probably shorten the expiration to 1 minute or less.

**Review by vbudhram — CHANGES_REQUESTED** [review]
@xlisachan Just some minor nits, but I do think we should lower the expiration.

**Comment by xlisachan** [comment]
Thanks for the feedback and for pairing with me on this ticket, @vbudhram ! I made the requested changes, please review when you have a moment. Thanks again!

**Review by vbudhram — APPROVED** [review]
@xlisachan Thank you! Please update the deploy docs. You will want to mention that the private key is the `.p8` file that is downloaded from Apple dev.
