### PR TITLE
fix(settings): updated bento logos

### LINKED ISSUE #6843: Get full color logo assets for bento menu
Current logos are from [https://github.com/mozilla/protocol-assets](https://github.com/mozilla/protocol-assets)

They do not look as nice as the logos on [https://monitor.firefox.com,](https://monitor.firefox.com,/) we need to get new assets in svg for our bento menu

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2670)
┆Issue Number: FXA-2670

### LINKED ISSUE #6866: [FxA-Settings] Incorrect Google Play Icon while the Bento Menu is displayed
**Build**
Stage [Train 1.193.0]

**Affected platforms**
Windows 10 64-bit

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Open the Bento Menu.
2. Scroll down at the bottom of the page and check the Google Play badge.

**Expected results**
The correct Google Play Icon is displayed - see figma.

**Actual Results**
Google Play icon displays a pink triangle.
issue31

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2674)
┆Issue Number: FXA-2674

### PR DESCRIPTION
**Pull request by dannycoates**
fixes #6843
fixes #6866

Before:
Screen Shot 2020-11-09 at 11 43 36 AM

After:
Screen Shot 2020-11-09 at 11 44 14 AM

### CODE REVIEW

File: packages/fxa-settings/src/components/BentoMenu/index.tsx [hunk 1]
```diff
@@ -7,12 +7,12 @@ import { useClickOutsideEffect } from 'fxa-react/lib/hooks';
...
-import { ReactComponent as PocketIcon } from './pocket.svg';
-import { ReactComponent as DesktopIcon } from './desktop.svg';
-import { ReactComponent as MobileIcon } from './mobile.svg';
-import { ReactComponent as LockwiseIcon } from './lockwise.svg';
+import firefoxIcon from 'fxa-react/images/ff-logo.svg';
+import monitorIcon from './monitor.svg';
+import pocketIcon from './pocket.svg';
+import desktopIcon from './desktop.svg';
+import mobileIcon from './mobile.svg';
+import lockwiseIcon from './lockwise.svg';
```
Comment (meandavejustice) [inline packages/fxa-settings/src/components/BentoMenu/index.tsx:15]: I like this syntax better, thanks for cleaning up

**Review by meandavejustice — APPROVED** [review]
Looks way better, thanks for fixing this up 🎉

**Comment by meandavejustice** [comment]
Looks like we just need some `alt` attributes added to the new img tags

```
./src/components/ConnectAnotherDevicePromo/index.tsx
  Line 36:11:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 43:11:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text

./src/components/BentoMenu/index.tsx
  Line 57:17:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 69:25:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 81:25:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 93:25:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 105:25:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 117:25:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text


```
