### PR TITLE
fix(payments): update payment views for mobile

### LINKED ISSUE #1832: (Updated) Mobile Screens
NOTE: These are not pixel perfect and should be used only as a reference point. They are not in Zeplin but if anyone needs pixel perfect Zeplin mobile screens don't hesitate to reach out and I will create them.

Please default to FxA styles where it makes more sense (i.e. button widths, padding, etc.)

Onboarding:
Onboarding (Mobile)

Subscription Page:
Subscriptions Page (Mobile)

Billing:
Billing (Mobile - filled out)

Support:
Support (Mobile - Filled out)

Subscription Termination:
Termination (Mobile)

Notifications:
Notification (Mobile)

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #1832

This is first pass at mobile screens in payment flow/support form. @janiceahn Feel free to ping me for changes if you don't wanna post them all here

phase-1-mobile-subscription-cancel-expanded
phase-1-mobile-subscription-payment-update-form
phase-1-mobile-subscription-home
phase-1-mobile-screens
phase-1-mobile-support

cc/ @janiceahn for UX review

### CODE REVIEW

**Comment by meandavejustice** [comment]
contact-dropdown-1
contact-dropdown-2
update-billing
cancel-sub

**Comment by juliastarkov** [comment]
@meandavejustice These look great, thanks for implementing the changes.

File: packages/fxa-payments-server/src/components/PaymentForm/index.tsx [hunk 1]
```diff
@@ -21,12 +21,13 @@ import {
...
 } from '../../lib/validator';
 import { formatCurrencyInCents } from '../../lib/formats';
+import { AppContext } from '../../lib/AppContext';
 
 import './index.scss';
 import { Plan } from '../../store/types';
 
 // ref: https://stripe.com/docs/stripe-js/reference#the-elements-object
-const STRIPE_ELEMENT_STYLES = {
+let stripeElementStyles = {
```
Comment (lmorchard) [inline packages/fxa-payments-server/src/components/PaymentForm/index.tsx]: I don't think this needs to be switched from const to let - the variable itself isn't reassigned, just properties of the object.

File: packages/fxa-payments-server/src/components/PaymentForm/index.tsx [hunk 2]
```diff
@@ -37,6 +38,15 @@ const STRIPE_ELEMENT_STYLES = {
   },
 };
 
+/* istanbul ignore next */
```
Comment (lmorchard) [inline packages/fxa-payments-server/src/components/PaymentForm/index.tsx]: This looks like something that *should* be covered in testing, not ignored

File: packages/fxa-payments-server/src/components/PaymentForm/index.tsx [hunk 3]
```diff
@@ -92,6 +104,9 @@ export const PaymentForm = ({
     [validator, onPayment, onPaymentError, stripe]
   );
 
+  /* istanbul ignore next */
```
Comment (lmorchard) [inline packages/fxa-payments-server/src/components/PaymentForm/index.tsx]: This should get covered in testing too, if only to assert that it's called with this string. Might also be good to move this string into a constant at the top of the file.

File: packages/fxa-payments-server/src/lib/AppContext.tsx [hunk 4]
```diff
@@ -20,6 +21,7 @@ export const defaultAppContext = {
   config,
   getScreenInfo: () => new ScreenInfo(),
   locationReload: noopFunction,
+  matchMedia: window.matchMedia || function() { return { matches: false }},
```
Comment (lmorchard) [inline packages/fxa-payments-server/src/lib/AppContext.tsx]: Don't refer to `window` here, just keep that isolated to `src/index.tsx` in the wrapper function. This default shouldn't get used in practice - both the app and tests should be providing a value, so `noopFunction` should work here.

File: packages/fxa-payments-server/src/routes/Product/index.test.tsx [hunk 5]
```diff
@@ -260,13 +264,15 @@ describe('routes/Product', () => {
...
       queryByText,
+      matchMedia,
       navigateToUrl,
       apiMocks,
     } = await commonSubmitSetup(createToken);
 
     fireEvent.click(getByTestId('submit'));
 
     await findByText('Your subscription is ready');
+    expect(matchMedia).toBeCalled();
```
Comment (lmorchard) [inline packages/fxa-payments-server/src/routes/Product/index.test.tsx]: This should probably be something like `expect(matchMedia).toBeCalledWith("(max-width: 480px)");` - or better yet, a constant imported from the component. 

Should also have a couple cases to mock `matchMedia` with both `true` & `false` results to exercise the `lineHeight` change in `checkMedia`

File: packages/fxa-payments-server/src/lib/test-utils.tsx [hunk 6]
```diff
@@ -182,6 +182,18 @@ export const defaultAppContextValue = (): AppContextType => ({
   accessToken: 'at_12345',
   config,
   queryParams: {},
+  matchMedia: jest.fn().mockImplementation(query => {
+    return {
+      matches: false,
+      media: query,
```
Comment (lmorchard) [inline packages/fxa-payments-server/src/lib/test-utils.tsx]: Does this mock need to have all these properties? Looks like ` jest.fn(() => { return { matches: false } })` is what's used everywhere else

File: packages/fxa-payments-server/src/lib/AppContext.tsx (hunk 4 above)
Comment (meandavejustice) [reply packages/fxa-payments-server/src/lib/AppContext.tsx]: noopFunction causes typescript to fail in this case :thinking:

File: packages/fxa-payments-server/src/lib/test-utils.tsx (hunk 6 above)
Comment (meandavejustice) [reply packages/fxa-payments-server/src/lib/test-utils.tsx]: These are necessary to prevent failures in typescript checks

File: packages/fxa-payments-server/src/lib/AppContext.tsx (hunk 4 above)
Comment (lmorchard) [reply packages/fxa-payments-server/src/lib/AppContext.tsx]: Hmm, also looks like `checkMedia` doesn't need the whole `MediaQueryList` object. Could just return `matches` from the wrapper in `src/index.tsx` and not have to cover the whole `MediaQueryList` object in types & mocks.

File: packages/fxa-payments-server/src/index.tsx [hunk 7]
```diff
@@ -59,6 +60,10 @@ function locationReload() {
   window.location.reload();
 }
 
+function matchMedia(query: string) {
+  return window.matchMedia(query);
```
Comment (lmorchard) [inline packages/fxa-payments-server/src/index.tsx]: If this was `return window.matchMedia(query).matches` then the type of this function could just be `(query: string) => boolean` and not drag in all of `MediaQueryList`

File: packages/fxa-payments-server/src/lib/test-utils.tsx (hunk 6 above)
Comment (lmorchard) [reply packages/fxa-payments-server/src/lib/test-utils.tsx]: Yeah, seems like that could be fixed by making the type simpler from the wrapper function in `src/index.tsx`

File: packages/fxa-payments-server/src/index.tsx (hunk 7 above)
Comment (meandavejustice) [reply packages/fxa-payments-server/src/index.tsx]: that would greatly simplify things, thank you

File: packages/fxa-payments-server/src/components/PaymentForm/index.tsx [hunk 8]
```diff
@@ -37,6 +42,11 @@ const STRIPE_ELEMENT_STYLES = {
   },
 };
 
+export function checkMedia(matched: boolean, stripeElementStyles: object) {
```
Comment (lmorchard) [inline packages/fxa-payments-server/src/components/PaymentForm/index.tsx]: Changes look good to me! :+1:

Comment (meandavejustice) [reply packages/fxa-payments-server/src/components/PaymentForm/index.tsx]: Thanks!
