### PR TITLE
fix(payments): use upcoming invoice for subscription reactivation price

### LINKED ISSUE #5914: Re-subscription email for an upgraded product lists the payment value before the upgrade
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.179.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have and active FxA account;

#### Steps to reproduce
1. Go to  https://123done-stage.dev.lcip.org/ page and make a subscription.
2. Load this page https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/products/prod_GVNS86uMUO3VRM using the same browser session.
3. Check  the “authorization” box. 
4. Click the “Confirm upgrade” blue button.
5. Load subscription page: https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions .
6. Click to cancel subscription for the 123done PRO PLUS product.
7. Click to resubscribe.
8. Load re-subscription email.

#### Expected result:
- The email contains the payment value specific to the product user upgraded too. (123done PRO PLUS - 500$)

#### Actual result:
- The email contains the payment value specific to the product before upgrade. (123done PRO - 5$)

lowerbill

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2268)
┆Issue Number: FXA-2268

### PR DESCRIPTION
**Pull request by lmorchard**
Using the last invoice for the next amount due on reactivating a
cancelled subscription is incorrect. The upcoming invoice has the
correct prorated price. This switches to that.

fixes #5914

### CODE REVIEW

File: packages/fxa-auth-server/lib/payments/stripe.ts [hunk 1]
```diff
@@ -1541,7 +1538,12 @@ class StripeHelper {
       invoiceTotalCurrency,
       cardType,
       lastFour,
-      nextInvoiceDate: new Date(nextInvoiceDate * 1000),
+      // TODO: According to Stripe, this value will be null for invoices where collection_method=send_invoice
```
Comment (lmorchard) [inline packages/fxa-auth-server/lib/payments/stripe.ts:1541]: This seems to work, but I *am* scratching my head at whether we'll hit this case where nextInvoiceDate is null on reactivating a cancelled subscription. Doesn't seem like any of our subscriptions should be collection_method=send_invoice, even if they're trial subscriptions?

**Comment by lmorchard** [comment]
Rebased against main to resolve conflicts. Will probably merge when CI is green
