### PR TITLE
fix(auth): use IAP scope for token register

### LINKED ISSUE #10202: Google token endpoint should use its own scope
The token endpoint incorrectly requires subscription scope access like we use for the checkout page, it should instead use a new subscription IAP permission.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3881)

### PR DESCRIPTION
**Pull request by bbangert**
Because:

* We should use a narrowly scoped permission for IAP token registration.

This commit:

* Adds a new scope for IAP access and applies it to the token
  registration endpoint.

Closes #10202

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

File: packages/fxa-shared/oauth/constants.js [hunk 1]
```diff
@@ -2,12 +2,15 @@
...
+  'https://identity.mozilla.com/account/subscriptions';
+
 module.exports = {
   OAUTH_SCOPE_OLD_SYNC: 'https://identity.mozilla.com/apps/oldsync',
   OAUTH_SCOPE_SESSION_TOKEN: 'https://identity.mozilla.com/tokens/session',
   OAUTH_SCOPE_NEWSLETTERS: 'https://identity.mozilla.com/account/newsletters',
-  OAUTH_SCOPE_SUBSCRIPTIONS:
-    'https://identity.mozilla.com/account/subscriptions',
+  OAUTH_SCOPE_SUBSCRIPTIONS,
+  OAUTH_SCOPE_SUBSCRIPTIONS_IAP: `${OAUTH_SCOPE_SUBSCRIPTIONS}:iap`,
```
Comment (dannycoates) [inline packages/fxa-shared/oauth/constants.js:13]: I was wrong originally about the `:` for url scopes, it should be `/` or `#`

https://github.com/mozilla/fxa/blob/main/packages/fxa-shared/oauth/scopes.js#L518

**Review by dannycoates — APPROVED** [review]
pre-approving, but we need to change the scope string
