### PR TITLE
fix(password): Add inline confirm password validation

### LINKED ISSUE #631: Validate password & vpassword inline instead of on form submit
Blocks https://github.com/mozilla/fxa-content-server/issues/6083

I suspect this could be handled on #vpassword blur. 

Other changes:
* Highlight both fields
* Attach the tooltip to the first field.

screen shot 2018-05-21 at 14 43 53

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #631 

inline_password

### CODE REVIEW

File: packages/fxa-content-server/app/scripts/views/sign_up_password.js [hunk 1]
```diff
@@ -30,6 +33,8 @@ const SignUpPasswordView = FormView.extend({
 
   events: assign({}, FormView.prototype.events, {
     'click .use-different': preventDefaultThen('useDifferentAccount'),
+    'keyup #vpassword': '_onConfirmPasswordKeyUp',
+    'blur #vpassword': '_onConfirmPasswordBlur',
```
Comment (vbudhram) [inline packages/fxa-content-server/app/scripts/views/sign_up_password.js]: I added check on blur because if user tabs to age input and the delay hasn't check it, it will automatically show the tooltip error. It seemed to be a little smoother.

File: packages/fxa-content-server/app/scripts/views/sign_up_password.js [hunk 2]
```diff
@@ -20,6 +20,9 @@ import Template from 'templates/sign_up_password.mustache';
 
 const t = msg => msg;
 
+const PASSWORD_INPUT_SELECTOR = '#vpassword';
+const DELAY_BEFORE_PASSWORD_CHECK_MS = 2000;
```
Comment (vbudhram) [inline packages/fxa-content-server/app/scripts/views/sign_up_password.js]: @ryanfeeley 2 seconds seem reasonable to me while manually testing. Any objections?

**Comment by vbudhram** [comment]
@mozilla/fxa-devs I think this is ready! r?

File: packages/fxa-content-server/app/scripts/views/sign_up_password.js [hunk 3]
```diff
@@ -104,6 +120,20 @@ const SignUpPasswordView = FormView.extend({
...
     return this._getPassword() === this._getVPassword();
   },
+
+  _onConfirmPasswordKeyUp() {
+    this.checkPasswordsMatchDebounce();
+  },
+
+  _onConfirmPasswordBlur() {
+    this._checkPasswordsMatch();
+  },
```
Comment (chenba) [inline packages/fxa-content-server/app/scripts/views/sign_up_password.js]: Does this mean the check is performed twice when I tab out of the confirm password field?  Once on the blur, and then again `DELAY_BEFORE_PASSWORD_CHECK_MS` after the last debounce call?

Comment (vbudhram) [reply packages/fxa-content-server/app/scripts/views/sign_up_password.js]: Hmm yea, it does. Let me add a few checks to make this work a little smoother.

**Comment by vbudhram** [comment]
@chenba made the updates!

**Comment by vbudhram** [comment]
@davismtl is this something you would like to get on train 150?

File: packages/fxa-content-server/app/scripts/views/sign_up_password.js [hunk 4]
```diff
@@ -104,6 +123,27 @@ const SignUpPasswordView = FormView.extend({
   _doPasswordsMatch() {
     return this._getPassword() === this._getVPassword();
   },
+
+  _onConfirmPasswordKeyUp() {
+    if (!passwordCheckLock) {
+      passwordCheckLock = true;
```
Comment (chenba) [inline packages/fxa-content-server/app/scripts/views/sign_up_password.js]: This changes the previous debounce behavior.  IIRC previously `debounce` is called on every keyup.  With this extra state, `debounce` is called on the first keyup, then again on the first keyup after `DELAY_BEFORE_PASSWORD_CHECK_MS`.  If the blur handler executes during the delay, it won't perform the check since `passwordCheckLock` will be true.

Is this intentional?

Comment (vbudhram) [reply packages/fxa-content-server/app/scripts/views/sign_up_password.js]: Yea this was intentional because otherwise you would see a slight flicker on the tooltip when called twice.

**Comment by vbudhram** [comment]
So on further investigating and testing, I am opting to remove the password match check on `blur`. This means that when a user tabs over to the age field, it will rely on the debounced password check rather than performing the check automatically. 

In practice it works wells and I don't see a huge difference. The second password field will get focused as part of the debounced function.

Keeping the original behavior did not play well with the first password field (you couldn't focus the input to change it). I think we can come up with a more general solution that will work for both password fields as part of the work @LZoog is doing.

cc @davismtl @mozilla/fxa-devs r?
