### PR TITLE
fix(tests): fix and re-enable sign_up_with_code.js

### LINKED ISSUE #7991: Functional test failures - Sign_up_with_code.js
┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3257)
┆Issue Number: FXA-3257

### PR DESCRIPTION
**Pull request by jaredhirsch**
Hitting the back button at the end of this particular test flow leaves you at the settings page, not the confirm page.

Fixes #7991.

### CODE REVIEW

File: packages/fxa-content-server/tests/functional.js [hunk 1]
```diff
@@ -81,13 +82,13 @@ module.exports = testsSettingsV2.concat([
...
+*/
 ]);
 
 // Mocha tests are only exposed during local dev, not on prod-like
 // instances such as latest, stable, stage, and prod. To avoid
 // Teamcity failing trying to run mocha tests, expose an environment
 // variable it can use to skip the mocha tests.
 if (!process.env.SKIP_MOCHA) {
-  module.exports.unshift('tests/functional/mocha.js');
+  //  module.exports.unshift('tests/functional/mocha.js');
```
Comment (dannycoates) [inline packages/fxa-content-server/tests/functional.js:93]: what's up with the mocha tests?

**Review by dannycoates — APPROVED** [review]

File: packages/fxa-content-server/tests/functional.js (hunk 1 above)
Comment (jaredhirsch) [reply packages/fxa-content-server/tests/functional.js:93]: ah, actually I have a commit in a branch that fixes them. Vijay caught one little bug, the others are just some navigate/navigateAway replacements. I'll go ahead and add that commit to this branch
