### PR TITLE
fix(settings): ensure modal callbacks adhere to the defined type

### LINKED ISSUE #7509: [Settings Redesign] Page crasher closing verified session modal
STR:

1. Be using an unverified session and at least two devices in the connected services list upon arriving at beta settings
1. Click "Sign out" on an item other than the current session
1. You should see the "Verify your email" modal
1. Click cancel or close the modal
1. General application error

Here's the first non-warning console error:

```
Uncaught Error: Objects are not valid as a React child (found: object with keys {dispatchConfig, _targetInst, _dispatchListeners,_ dispatchInstances, nativeEvent, type, target, currentTarget, eventPhase, bubbles, cancelable, timeStamp, defaultPrevented, isTrusted, view, detail, screenX, screenY, clientX, clientY, pageX, pageY, ctrlKey, shiftKey, altKey, metaKey, getModifierState, button, buttons, relatedTarget, movementX, movementY, isDefaultPrevented, isPropagationStopped}). If you meant to render a collection of children, use an array instead. in p (at ConnectedServices/index.tsx:288) in div (at AlertBar/index.tsx:57) in div (at AlertBar/index.tsx:47) in div (at AlertBar/index.tsx:42) in AlertBar (at ConnectedServices/index.tsx:287) in div (at ConnectedServices/index.tsx:231) in section (at ConnectedServices/index.tsx:226) in ConnectedServices (at PageSettings/index.tsx:36) in div (at PageSettings/index.tsx:33) in div (at PageSettings/index.tsx:28) in PageSettings (at App/index.tsx:74) in div (created by FocusHandlerImpl) in FocusHandlerImpl (created by Context.Consumer) in FocusHandler (created by RouterImpl) in RouterImpl (created by Context.Consumer) in Location (created by Context.Consumer) in Router (created by RouterImpl) in ScrollToTop (at App/index.tsx:73) in div (created by FocusHandlerImpl) in FocusHandlerImpl (created by Context.Consumer) in FocusHandler (created by RouterImpl) in RouterImpl (created by LocationProvider) in LocationProvider (created by Context.Consumer) in Location (created by Context.Consumer) in Router (at App/index.tsx:72) in main (at AppLayout/index.tsx:25) in div (at AppLayout/index.tsx:24) in div (at AppLayout/index.tsx:18) in AppLayout (at App/index.tsx:70) in LocalizationProvider (at AppLocalizationProvider.tsx:125) in AppLocalizationProvider (at App/index.tsx:66) in App (at src/index.tsx:84) in AppErrorBoundary (at src/index.tsx:83) in ApolloProvider (at src/index.tsx:80) in StrictMode (at src/index.tsx:79)
```

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3034)
┆Issue Number: FXA-3034

### PR DESCRIPTION
**Pull request by dannycoates**
The `Modal` and `ModalVerifySession` components were incidentally calling the `onDismiss` callback with the dom event argument from their originating element. This happened to break the `ConnectedServices` component which was using a fn that accepted optional parameters as the callback.

This commit ensures the callbacks are called with no arguments.

fixes #7509

### CODE REVIEW

**Comment by dannycoates** [comment]
I need to fix the collateral damage from making `onConfirm` take no args.

File: packages/fxa-settings/src/components/ConnectedServices/index.tsx [hunk 1]
```diff
@@ -112,31 +102,26 @@ export const ConnectedServices = () => {
     hideAdviceModal,
   ] = useBooleanState();
 
+  // You'd think that you could have client be from useState but due to how useMutation works
+  // the value of the state inside the update function is unpredicatable. A ref is more
```
Comment (6a68) [inline packages/fxa-settings/src/components/ConnectedServices/index.tsx:106]: typo: "unpredictable"

also, :coolcry:

File: packages/fxa-settings/src/components/ConnectedServices/index.tsx [hunk 2]
```diff
@@ -112,31 +102,26 @@ export const ConnectedServices = () => {
...
+
   const clearDisconnectingState = (
     errorMessage?: string,
     error?: ApolloError
   ) => {
     hideConfirmDisconnectModal();
-    DS.client = null;
-    DS.reason = null;
+    client.current = undefined;
+    setReason(undefined);
```
Comment (6a68) [inline packages/fxa-settings/src/components/ConnectedServices/index.tsx:117]: Optional: it can be nice to set things to `null` rather than `undefined`, so that when debugging, it's easy to tell if a variable was accidentally never set (undefined), or was deliberately set to a falsy value (null).

File: packages/fxa-settings/src/components/ConnectedServices/index.tsx [hunk 3]
```diff
@@ -112,31 +102,26 @@ export const ConnectedServices = () => {
...
-        'input[type="radio"]:checked'
-      ) as HTMLInputElement;
-      if (selected) {
-        DS.reason = selected.value;
-      }
-    }
-
-    if (!DS.client) {
+  const onConfirmDisconnect = () => {
+    if (!client.current) {
```
Comment (6a68) [inline packages/fxa-settings/src/components/ConnectedServices/index.tsx:124]: Wow, this is so much nicer than fishing the state out of the DOM 🎉

File: packages/fxa-settings/src/components/ConnectedServices/index.tsx [hunk 4]
```diff
@@ -182,15 +170,15 @@ export const ConnectedServices = () => {
       onCompleted: () => {
         // TODO: Add `timing.clients.disconnect` flow timing event as seen in
         // old-settings? #6903
-        if (DS.client!.isCurrentSession) {
+        if (client.current?.isCurrentSession) {
           clearSignedInAccountUid();
           window.location.assign(`${window.location.origin}/signin`);
-        } else if (DS.reason === 'suspicious' || DS.reason === 'lost') {
+        } else if (reason === 'suspicious' || reason === 'lost') {
```
Comment (6a68) [inline packages/fxa-settings/src/components/ConnectedServices/index.tsx:176]: Optional: should we use an enum for the reason, instead of a string?

**Review by 6a68 — APPROVED** [review]
LGTM, couple optional/minor things

File: packages/fxa-settings/src/components/ConnectedServices/index.tsx (hunk 4 above)
Comment (dannycoates) [reply packages/fxa-settings/src/components/ConnectedServices/index.tsx:176]: meh
