### PR TITLE
fix(emails): Fix the resend secondary email code button

### LINKED ISSUE #4365: No email is sent when clicking on “Need another code? Resend” link
**Note:**
This is a follow-up up for #2653

**Build:**
Stage [Train 1.160.0]

**Affected platforms:**
Windows 10

**Steps to reproduce:**
1. Create and confirm a new Firefox account.
2. Go to the email inbox and open the "Set up recovery email" email.
3. Click on the “Add a secondary email” button.
4. Add a different email address in the field and tap on "Continue".
5. Click on “Need another code? Resend” link.

**Expected results:**
2 "Confirm secondary email" emails are received.

**Actual Results:**
Only one “Confirm secondary email” email is received and no email is sent when clicking on “Need another code? Resend” link.

resendemail

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1261)
┆Issue Number: FXA-1261

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #4365

### CODE REVIEW

File: packages/fxa-content-server/app/tests/spec/views/post_verify/secondary_email/confirm_secondary_email.js [hunk 1]
```diff
@@ -138,6 +138,24 @@ describe('views/post_verify/secondary_email/confirm_secondary_email', () => {
     });
   });
 
+  describe('resend', () => {
+    describe('resend', () => {
```
Comment (dannycoates) [inline packages/fxa-content-server/app/tests/spec/views/post_verify/secondary_email/confirm_secondary_email.js]: why the double `describe`?
