### PR TITLE
fix(scoped-keys): Allow clients to provide `keys_jwk` when not requesting scoped keys.

### LINKED ISSUE #1792: Disable "No-key bearing scopes" requested check
Ref: https://github.com/mozilla/application-services/issues/1400#issuecomment-511253606

### PR DESCRIPTION
**Pull request by rfk**
Based on experience implementing consuming code, it's much more convenient to be able to always pass in `keys_jwk` than it is to require the client code to decide up-front whether any of its requested scopes will have keys.

This removes some "belt and braces" check that were enforcing clients the provide `keys_jwk` if and only if requesting a key-bearing scope, and instead just ignores `keys_jwk` when not requesting any key-bearing scopes.

Fixes #1792.

@vladikoff does this fit with what you were thinking?

### CODE REVIEW

File: packages/fxa-content-server/app/scripts/models/reliers/oauth.js [hunk 1]
```diff
@@ -317,16 +318,16 @@ var OAuthRelier = Relier.extend({
     return !!(
       this._config &&
       this._config.scopedKeysEnabled &&
-      this.has('keysJwk')
+      this.has('keysJwk') &&
+      this._wantsScopeThatHasKeys
```
Comment (rfk) [inline packages/fxa-content-server/app/scripts/models/reliers/oauth.js]: This extra check prevents us from allocating a `keyFetchToken` if the relier doesn't actually want any keys.

File: packages/fxa-content-server/app/scripts/models/reliers/oauth.js [hunk 2]
```diff
@@ -340,31 +341,25 @@ var OAuthRelier = Relier.extend({
...
     }
 
-    const validation = this._config.scopedKeysValidation || {};
-    let foundRedirectScopeMatch = false;
-
-    // Requesting keys, but not specifying a scope?  That's unexpected.
+    // If they're not requesting any scopes, we're not going to given them any keys.
     if (!this.get('scope')) {
-      throw new Error('Invalid scope parameter');
+      return false;
```
Comment (vladikoff) [inline packages/fxa-content-server/app/scripts/models/reliers/oauth.js]: 👍

**Comment by rfk** [comment]
> Did you want to uplift it to an earlier train instead of master, 

I don't think it's worth adding risk to train-141, which is already getting some point-releases in support of time-sensitive projects.
