### PR TITLE
fix(tv): fixed some ui glitches on Fire TV

### LINKED ISSUE #2013: Can't sign up on FFTV due to focus issue
### Steps to Reproduce

1. Open FFTV pointed at https://latest.dev.lcip.org/ (here's an APK https://drive.google.com/file/d/1IIdMoVjbNtWKmE1H76XKjRRAMfZu5EsL/view?usp=sharing )
2. Click "Receive Tabs" in toolbar or go to https://www.mozilla.org/en-CA/firefox/accounts/
3. Click sign up
4. Enter Email
5. Click Continue

### Expected Behaviour

You are taken to "Create a Firefox Account" page and "Password" field is focused

### Actual Behaviour

You are taken to "Create a Firefox Account" page, but no field is focused. 

Using the remote arrows, you can reach “terms of service”, “create account” or “mistyped email?” You can't reach the "password" field because the focus gets stuck on "how old are you"

7-30-fxa-flow

### PR DESCRIPTION
**Pull request by dannycoates**
This temporarily disables the password strength on small screens until a better design can be implemented.

@ryanfeeley I'm happy to re-enable and change the strength balloon once we have a solution. This is just a quick fix to unblock Fire TV.

fixes #2013

### CODE REVIEW

File: packages/fxa-content-server/app/scripts/views/mixins/coppa-mixin.js [hunk 1]
```diff
@@ -121,6 +121,8 @@ export default function(config = {}) {
           keyCode === KeyCodes.TAB ||
           keyCode === KeyCodes.LEFT_ARROW ||
           keyCode === KeyCodes.RIGHT_ARROW ||
+          keyCode === KeyCodes.UP_ARROW ||
+          keyCode === KeyCodes.DOWN_ARROW ||
```
Comment (dannycoates) [inline packages/fxa-content-server/app/scripts/views/mixins/coppa-mixin.js]: missing these caused the coppa to be a black hole for the remote control

File: packages/fxa-content-server/app/styles/_breakpoints.scss [hunk 2]
```diff
@@ -5,9 +5,9 @@ $breakpoints: (
     '(max-width: 520px), (max-height: 640px), (orientation: landscape) and (min-width: 641px) and (max-height: 640px)',
   big: '(min-width: 521px) and (min-height: 641px)',
   balloonSmall: '(max-width: 960px)',
-  balloonBig: '(min-width: 960px)',
+  balloonBig: '(min-width: 961px)',
```
Comment (dannycoates) [inline packages/fxa-content-server/app/styles/_breakpoints.scss]: not explicitly necessary while the balloon is disabled, but when the screen was exactly 960px (as the TV is) both small and big selectors were triggered

File: packages/fxa-content-server/app/scripts/views/mixins/password-strength-mixin.js [hunk 3]
```diff
@@ -32,6 +32,11 @@ export default function(config = {}) {
           // problems in the reset-password screen when using the recovery key
           return;
         }
+        if (window.matchMedia('(max-width: 960px)').matches) {
```
Comment (shane-tomlinson) [inline packages/fxa-content-server/app/scripts/views/mixins/password-strength-mixin.js]: Eh? I think it will make @ryanfeeley sad to disable the balloon universally on mobile devices. The balloon is supposed to go away once the password is valid, is that broken? See also https://github.com/mozilla/fxa/issues/1470.

Comment (dannycoates) [reply packages/fxa-content-server/app/scripts/views/mixins/password-strength-mixin.js]: It's broken on TV because it prevents you from completing the form at all. I'm happy to fix it but my priority is to unblock them and follow up with a working balloon

Comment (shane-tomlinson) [reply packages/fxa-content-server/app/scripts/views/mixins/password-strength-mixin.js]: Can we UA sniff? Gross, but doesn't kill the feature for everyone.

Comment (dannycoates) [reply packages/fxa-content-server/app/scripts/views/mixins/password-strength-mixin.js]: Seems broken for everyone to me with #1470

Comment (ryanfeeley) [reply packages/fxa-content-server/app/scripts/views/mixins/password-strength-mixin.js]: This UI needs some TLC. The repeat password message should disappear when the basic requirements are met (for the second field that means the password is repeated). Original design: https://mozilla.invisionapp.com/share/5UM3J3TXWMR#/316338169_Artboard

Comment (shane-tomlinson) [reply packages/fxa-content-server/app/scripts/views/mixins/password-strength-mixin.js]: > Seems broken for everyone to me with #1470

In the bugzilla bug I asked the user if the password bubble goes away if the requirements are met. Yes, yes they do.

> I just tried it again, and it does indeed go away when the requirements are met. I still maintain the interface is surprising. Covering form elements with a little box like that so you cannot click on them is not a common way to communicate that elements are not available or enabled. Perhaps showing those elements but graying them out would be a more effective way to communicate the message. However, if you don't consider this a bug, I suppose it's not a bug. Thanks for taking a look.

Comment (dannycoates) [reply packages/fxa-content-server/app/scripts/views/mixins/password-strength-mixin.js]: There isn't anything very unique about the ua string on TV.
`Mozilla/5.0 (Linux; Android 7.1.2) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.2-LAT1 Chrome/59.0.3071.125 Mobile Safari/537.36` (`Focus` is the closest thing worth filtering on I suppose)

I don't see anything wrong with disabling it on mobile until it's fixed. It's obviously causing enough confusion for someone to file a bug, even if it technically works.

Comment (dannycoates) [reply packages/fxa-content-server/app/scripts/views/mixins/password-strength-mixin.js]: If we merge this after the train I may even have the bubble fixed before the next train. Really, I just want this on `latest`

Comment (shane-tomlinson) [reply packages/fxa-content-server/app/scripts/views/mixins/password-strength-mixin.js]: > If we merge this after the train I may even have the bubble fixed before the next train. Really, I just want this on latest

You've convinced me! r+

**Comment by dannycoates** [comment]
@shane-tomlinson instead of doing a new PR I just added a new commit here that fixes the password balloon.

fixes #2051 
fixes #2022

File: packages/fxa-content-server/app/scripts/views/mixins/coppa-mixin.js (hunk 1 above)
Comment (shane-tomlinson) [reply packages/fxa-content-server/app/scripts/views/mixins/coppa-mixin.js]: The best part about this change is that up/down arrow on Fx Desktop now cause the value to increment/decrement as you'd expect in a number input! 💯

File: packages/fxa-content-server/app/scripts/views/password_strength/password_with_strength_balloon.js [hunk 4]
```diff
@@ -70,9 +70,10 @@ const PasswordWithStrengthBalloonView = FormView.extend({
       // which causes the check to occur a 2nd time.
       return !!this.model.validate({ password });
     }
-
-    // There is no prefilled password, yes, show the balloon.
-    return true;
+    // when css `respond-to('balloonSmall') wait until the password
```
Comment (shane-tomlinson) [inline packages/fxa-content-server/app/scripts/views/password_strength/password_with_strength_balloon.js]: 👍 This is a great approach.
