### PR TITLE
fix(emails): sentence-case and simplify the email subjects

### LINKED ISSUE #1684: Inconsistent casing of subject lines in emails
Most of the FxA emails have the subject line in sentence-casing. But while reviewing #1675, I noticed that "Finish Creating Your Account", "Reminder: Finish Creating Your Account" and "Your Firefox Account is Confirmed" have title-casing.

It looks like it's how they were specified in the designs for #1073 / #1087, but that seems weirdly inconsistent to me. Is it a bug or a feature?

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #1684.

~~This is waiting on a couple of outstanding UX decisions so it's not ready for review yet.~~

But fwiw, it updates the email subjects to use sentence casing and simplifies a number of them. 

More discussion in the linked issue and [the spreadsheet](https://docs.google.com/document/d/1LRf1SiFg3zxJbDVFbilCUVDKjKcRt4_cnT_epzKm684/edit).

### CODE REVIEW

File: packages/fxa-auth-server/lib/senders/email.js [hunk 1]
```diff
@@ -333,7 +333,11 @@ module.exports = function(log, config, oauthdb) {
     return {
       html: localized.html,
       language: translator.language,
-      subject: translator.gettext(message.subject),
+      subject: translator.format(
```
Comment (philbooth) [inline packages/fxa-auth-server/lib/senders/email.js]: Since there's now more than one subject that includes data, I moved the call to `format` up here to eliminate duplicate calling code.

File: packages/fxa-auth-server/lib/senders/email.js [hunk 2]
```diff
@@ -1248,12 +1246,7 @@ module.exports = function(log, config, oauthdb) {
 
     return oauthClientInfo.fetch(message.service).then(clientInfo => {
       const clientName = clientInfo.name;
-      const subject = translator.format(
```
Comment (philbooth) [inline packages/fxa-auth-server/lib/senders/email.js]: (...and hence this call is removed)

File: packages/fxa-auth-server/test/local/senders/email.js [hunk 3]
```diff
@@ -2494,11 +2494,8 @@ describe('email translations', () => {
           'language header is correct'
         );
         // NOTE: translation might change, but we use the subject, we don't change that often.
-        assert.equal(
-          emailConfig.subject,
-          'أكّد حساب فَيَرفُكس الخاص بك',
-          'translation is correct'
-        );
+        // TODO: switch back to testing the subject when translations have caught up
+        assert.include(emailConfig.text, 'سياسة موزيلا للخصوصيّة');
```
Comment (philbooth) [inline packages/fxa-auth-server/test/local/senders/email.js]: There were a couple of awkward changes where we're testing translated text, but now we've temporarily broken those assertions until the translators do their thing. For arabic, I couldn't find another matching subject line that was translated, so testing the translation for `Mozilla Privacy Policy` instead.

File: packages/fxa-auth-server/test/local/senders/email.js [hunk 4]
```diff
@@ -2514,14 +2511,13 @@ describe('email translations', () => {
...
-          'Подтвердите ваш Аккаунт Firefox',
-          'translation is correct'
-        );
+        assert.equal(emailConfig.subject, 'Завершите создание вашего Аккаунта');
       });
 
-      return mailer['verifyEmail'](message);
+      return mailer['verifyEmail']({
+        ...message,
+        style: 'trailhead',
```
Comment (philbooth) [inline packages/fxa-auth-server/test/local/senders/email.js]: For Russian, there was a translated subject available, but trailhead-specific.

**Comment by philbooth** [comment]
@mozilla/fxa-devs, this contain string changes that I want to land before the deadline.

Note that in one case, the linked spreadsheet also talked about making behavioural changes (to the low recovery codes email). I've purposefully scoped this to just the string changes, to keep things simple here. We can make follow-ups for any bigger, behavioural changes.

File: packages/fxa-auth-server/lib/senders/email.js [hunk 5]
```diff
@@ -1601,7 +1594,7 @@ module.exports = function(log, config, oauthdb) {
     return this.send(
       Object.assign({}, message, {
         headers,
-        subject: gettext('Low recovery codes remaining'),
+        subject: gettext('Low Recovery Codes Remaining'),
```
Comment (shane-tomlinson) [inline packages/fxa-auth-server/lib/senders/email.js]: I know you didn't specify the text, `Low` doesn't seem like the right word here. It seems like `Few` would be more suitable, or `Create More Recovery Codes to Avoid Lockout`

**Comment by shane-tomlinson** [comment]
Looks like the [auth-server tests are failing](https://circleci.com/gh/mozilla/fxa/55727)

Here is one error:

>  3) remote account signin verification
       sign-in verification email link:

      AssertionError: expected 'Confirm New Sign-in' to equal 'Confirm new sign-in to Firefox'
      + expected - actual

      -Confirm New Sign-in
      +Confirm new sign-in to Firefox
      
      at Client.createAndVerify.then.then.then.then.emailData (test/remote/account_signin_verification_tests.js:282:16)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:694:18)
      at _drainQueueStep (node_modules/bluebird/js/release/async.js:138:12)
      at _drainQueue (node_modules/bluebird/js/release/async.js:131:9)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:147:5)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
      at process.topLevelDomainCallback (domain.js:126:23)


Looks like the content server failure is due to https://github.com/mozilla/fxa/issues/2031

File: packages/fxa-auth-server/lib/senders/email.js (hunk 5 above)
Comment (philbooth) [reply packages/fxa-auth-server/lib/senders/email.js]: This is related to the behavioural change that I mentioned in https://github.com/mozilla/fxa/pull/2017#issuecomment-517201294.

I've compromised, so this now reads `%(numberRemaining)s Recovery Codes Remaining` instead.

**Comment by philbooth** [comment]
@mozilla/fxa-devs r?

File: packages/fxa-auth-server/scripts/write-emails-to-disk.js [hunk 6]
```diff
@@ -123,6 +123,7 @@ function sendMail(mailer, messageToSend) {
       country: 'Spain',
     },
     locations: [],
+    numberRemaining: 2,
```
Comment (shane-tomlinson) [inline packages/fxa-auth-server/scripts/write-emails-to-disk.js]: ❤️ - thank you, I used the script to check the titles!

Comment (philbooth) [reply packages/fxa-auth-server/scripts/write-emails-to-disk.js]: Ha, I leaned on it a lot recently for #1791 too, so it was at the front of mind.
