### PR TITLE
fix(style): use svg for close modal icon

### LINKED ISSUE #2982: Fix Subscription Modal Close
Subscription modal dismiss button is 

* too small, should be 24 x 24
* should use an x icon (provided) rather than the letter x
```
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"><path fill="rgba(12, 12, 13, .8)" d="M9.414 8l5.293-5.293a1 1 0 00-1.414-1.414L8 6.586 2.707 1.293a1 1 0 00-1.414 1.414L6.586 8l-5.293 5.293a1 1 0 101.414 1.414L8 9.414l5.293 5.293a1 1 0 001.414-1.414z"/></svg>
```

### PR DESCRIPTION
**Pull request by chenba**
Use a svg as the close modal icon instead of using an X character.  This
applies to both content and payments servers.

Fixes #2982

### CODE REVIEW

File: packages/fxa-payments-server/src/routes/Subscriptions/index.tsx [hunk 1]
```diff
@@ -238,16 +239,11 @@ export const Subscriptions = ({
...
+      {updatePaymentStatus.result && (
         <AlertBar className="alert alertSuccess alertCenter">
           <span data-testid="success-billing-update" className="checked">
             Your billing information has been updated successfully
           </span>
-          <span
-            data-testid="clear-success-alert"
-            className="close"
-            onClick={clearSuccessAlert}
-          />
```
Comment (chenba) [inline packages/fxa-payments-server/src/routes/Subscriptions/index.tsx]: This and its associated state, onclick handler, and styles are removed because the alert bar now self-dismisses.

Related to https://github.com/mozilla/fxa/issues/3187.

File: packages/fxa-payments-server/src/components/DialogMessage.tsx [hunk 2]
```diff
@@ -20,10 +21,21 @@ export const DialogMessage = ({
...
+      >
+        <div
+          data-testid="dialog-message-content"
+          className={classNames('modal', className)}
+          ref={dialogInsideRef}
+        >
+          <button
+            data-testid="dialog-dismiss"
+            className="dismiss"
+            onClick={onDismiss as () => void}
```
Comment (LZoog) [inline packages/fxa-payments-server/src/components/DialogMessage.tsx]: Can we add an `aria-label="Close modal"` on here? Looks good otherwise!

FWIW, I have an accessibility epic open for payments and haven't had a chance yet to finish an audit, if you want to get this merged (per your comment in #3187) will you create an issue and add it to #2963? Thanks!

Comment (chenba) [reply packages/fxa-payments-server/src/components/DialogMessage.tsx]: 👍  Add #3227 to the accessibility epic.
