### PR TITLE
fix(metrics): send nav timing as text/plain

### LINKED ISSUE #4522: Failure to load payments page in production
This was reported by a user and I am able to reproduce in Firefox, Chrome and Safari

From the user:

> Weird, I still can't get anything to come up now when using FF on Windows. Every time I hit the 'Subscribe Now' button from the invite page, it seems like it loads but the webpage is blank. On my phone I can connect to the page but the elements are all broken and can't click anything. Should I just join the wait list again?
> So I am seeing issues on Chrome, Safari and Intermittently on Firefox, but caveat here is that I have to use a VPN to get to the FPN site due to my location...Firefox and Chrome errors are logged below.

## Firefox
```
logger.js:72 No Sentry dsn provided
error @ logger.js:72
p @ sentry.js:114
45 @ flow-event.ts:4
c @ bootstrap:89
21 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
19 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
102 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
80 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
r @ bootstrap:45
t @ bootstrap:32
(anonymous) @ main.e6fef031.chunk.js:1
logger.js:72 No Sentry dsn provided
error @ logger.js:72
p @ sentry.js:114
21 @ amplitude.ts:5
c @ bootstrap:89
19 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
102 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
80 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
r @ bootstrap:45
t @ bootstrap:32
(anonymous) @ main.e6fef031.chunk.js:1
logger.js:72 No Sentry dsn provided
error @ logger.js:72
p @ sentry.js:114
102 @ App.tsx:29
c @ bootstrap:89
80 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
r @ bootstrap:45
t @ bootstrap:32
(anonymous) @ main.e6fef031.chunk.js:1
index.tsx:123 accessToken verified
react-dom.production.min.js:4636 DOMException: Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not any of the CORS-safelisted values for the Content-Type request header is disabled temporarily. See http://crbug.com/490015 for details.
 at ce (https://subscriptions.firefox.com/static/js/main.e6fef031.chunk.js:1:7543)
 at ie (https://subscriptions.firefox.com/static/js/main.e6fef031.chunk.js:1:7719)
 at fe (https://subscriptions.firefox.com/static/js/main.e6fef031.chunk.js:1:9293)
 at ha (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:176380)
 at Cu (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:221816)
 at Rc (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:207336)
 at Pc (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:207261)
 at _c (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:204581)
 at yc (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:201325)
 at ol (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:229399)
yu @ react-dom.production.min.js:4636
n.callback @ react-dom.production.min.js:5081
ki @ react-dom.production.min.js:3059
xi @ react-dom.production.min.js:3047
Dc @ react-dom.production.min.js:6345
t.unstable_runWithPriority @ scheduler.production.min.js:270
Qo @ react-dom.production.min.js:2794
Mc @ react-dom.production.min.js:6105
_c @ react-dom.production.min.js:5408
yc @ react-dom.production.min.js:5191
ol @ react-dom.production.min.js:7059
(anonymous) @ react-dom.production.min.js:7155
xc @ react-dom.production.min.js:5444
sl @ react-dom.production.min.js:7154
render @ react-dom.production.min.js:7291
(anonymous) @ index.tsx:30
l @ runtime.js:45
(anonymous) @ runtime.js:264
E.forEach.e.<computed> @ runtime.js:98
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
index.tsx:129 init error DOMException: Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not any of the CORS-safelisted values for the Content-Type request header is disabled temporarily. See http://crbug.com/490015 for details.
 at ce (https://subscriptions.firefox.com/static/js/main.e6fef031.chunk.js:1:7543)
 at ie (https://subscriptions.firefox.com/static/js/main.e6fef031.chunk.js:1:7719)
 at fe (https://subscriptions.firefox.com/static/js/main.e6fef031.chunk.js:1:9293)
 at ha (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:176380)
 at Cu (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:221816)
 at Rc (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:207336)
 at Pc (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:207261)
 at _c (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:204581)
 at yc (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:201325)
 at ol (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:229399)
```

## Chrome

```
logger.js:72 No Sentry dsn provided
error @ logger.js:72
p @ sentry.js:114
45 @ flow-event.ts:4
c @ bootstrap:89
21 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
19 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
102 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
80 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
r @ bootstrap:45
t @ bootstrap:32
(anonymous) @ main.e6fef031.chunk.js:1
logger.js:72 No Sentry dsn provided
error @ logger.js:72
p @ sentry.js:114
21 @ amplitude.ts:5
c @ bootstrap:89
19 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
102 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
80 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
r @ bootstrap:45
t @ bootstrap:32
(anonymous) @ main.e6fef031.chunk.js:1
logger.js:72 No Sentry dsn provided
error @ logger.js:72
p @ sentry.js:114
102 @ App.tsx:29
c @ bootstrap:89
80 @ main.e6fef031.chunk.js:1
c @ bootstrap:89
r @ bootstrap:45
t @ bootstrap:32
(anonymous) @ main.e6fef031.chunk.js:1
index.tsx:123 accessToken verified
react-dom.production.min.js:4636 DOMException: Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not any of the CORS-safelisted values for the Content-Type request header is disabled temporarily. See http://crbug.com/490015 for details.
 at ce (https://subscriptions.firefox.com/static/js/main.e6fef031.chunk.js:1:7543)
 at ie (https://subscriptions.firefox.com/static/js/main.e6fef031.chunk.js:1:7719)
 at fe (https://subscriptions.firefox.com/static/js/main.e6fef031.chunk.js:1:9293)
 at ha (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:176380)
 at Cu (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:221816)
 at Rc (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:207336)
 at Pc (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:207261)
 at _c (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:204581)
 at yc (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:201325)
 at ol (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:229399)
yu @ react-dom.production.min.js:4636
n.callback @ react-dom.production.min.js:5081
ki @ react-dom.production.min.js:3059
xi @ react-dom.production.min.js:3047
Dc @ react-dom.production.min.js:6345
t.unstable_runWithPriority @ scheduler.production.min.js:270
Qo @ react-dom.production.min.js:2794
Mc @ react-dom.production.min.js:6105
_c @ react-dom.production.min.js:5408
yc @ react-dom.production.min.js:5191
ol @ react-dom.production.min.js:7059
(anonymous) @ react-dom.production.min.js:7155
xc @ react-dom.production.min.js:5444
sl @ react-dom.production.min.js:7154
render @ react-dom.production.min.js:7291
(anonymous) @ index.tsx:30
l @ runtime.js:45
(anonymous) @ runtime.js:264
E.forEach.e.<computed> @ runtime.js:98
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
index.tsx:129 init error DOMException: Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not any of the CORS-safelisted values for the Content-Type request header is disabled temporarily. See http://crbug.com/490015 for details.
 at ce (https://subscriptions.firefox.com/static/js/main.e6fef031.chunk.js:1:7543)
 at ie (https://subscriptions.firefox.com/static/js/main.e6fef031.chunk.js:1:7719)
 at fe (https://subscriptions.firefox.com/static/js/main.e6fef031.chunk.js:1:9293)
 at ha (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:176380)
 at Cu (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:221816)
 at Rc (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:207336)
 at Pc (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:207261)
 at _c (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:204581)
 at yc (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:201325)
 at ol (https://subscriptions.firefox.com/static/js/4.fab6de7e.chunk.js:1:229399)
 
```

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1351)
┆Issue Number: FXA-1351

### PR DESCRIPTION
**Pull request by chenba**
This patch updates the navigation timing reporting request to send its
content as text/plain.  Some users were seeing blank pages on Payments
due to errors caused by the blob's content-type.

Fixes #4522 (FXA-1351)

@mozilla/fxa-devs r?

### CODE REVIEW

File: packages/fxa-payments-server/server/lib/routes/navigation-timing.js [hunk 1]
```diff
@@ -7,10 +7,7 @@
 const joi = require('joi');
 const URL = require('url').URL;
 
-const TIMESTAMP_MS = joi
-  .number()
-  .integer()
-  .required();
+const TIMESTAMP_MS = joi.number().required();
```
Comment (chenba) [inline packages/fxa-payments-server/server/lib/routes/navigation-timing.js]: Chrome's numbers are super hi-res so we cannot use integer here.

**Comment by chenba** [comment]
Yeah.  Since tagging is later today, I think this is good to go for that release.
