### PR TITLE
fix(auth): user Sent Unnecessary Finish Setting Up Account Reminder Email

### LINKED ISSUE #12802: User keeps getting asked to set up a password even after creating it
userid is <redacted>

This user has signed up for the VPN service recently and set up their password.

As per now, they are able to login and use the VPN app as well as the FxA services with the email address and password created

Regardless, it seems like we keep sending them emails asking to create a password - see screenshot attached

Can this please be reviewed?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5052)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23621">email_screenshot.PNG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23622">Final reminder Setup your account (1).eml</a>

### PR DESCRIPTION
**Pull request by IvoJP**
Because:

* users are receiving unnecessary emails after creating a password (likely due to an error occuring after their account is verified but before their reminder is removed OR an issue with not dropping the key from redis)

This commit:

* adds an additional attempt to drop the key from redis if an error occurs after the account is verified and adds a check to see if the account is verified before sending the email

Closes #12802

## Checklist

_Put an `x` in the boxes that apply_

- [X] My commit is GPG signed.
- [X] If applicable, I have modified or added tests which pass locally.
- [X] I have added necessary documentation (if appropriate).
- [X] I have verified that my changes render correctly in RTL (if appropriate).

## Other information (Optional)
I was not able to reproduce this locally but I think was I able to narrow it down to 2 possible issues that COULD occur: the first that there is an error when the user is finishing setting up their account between where the account is verified and where we drop the key from redis to send out a reminder email OR the second where we fail to drop the key. I added 2 checks in here to hopefully handle either scenario.

### CODE REVIEW

File: packages/fxa-auth-server/lib/senders/email.js [hunk 1]
```diff
@@ -658,6 +658,7 @@ module.exports = function (log, config, bounces) {
         flowId,
         flowBeginTime,
         deviceId,
+        accountVerified,
```
Comment (StaberindeZA) [inline packages/fxa-auth-server/lib/senders/email.js:661]: When this function is called, do we know that `accountVerified` is added to `message`?

File: packages/fxa-auth-server/lib/routes/account.ts [hunk 2]
```diff
@@ -578,12 +578,13 @@ export class AccountHandler {
     this.log.begin('Account.finishSetup', request);
     const form = request.payload as any;
     const authPW = form.authPW;
+    let uid;
```
Comment (StaberindeZA) [inline packages/fxa-auth-server/lib/routes/account.ts:581]: Is this additional variable necessary? Could you just use `payload.uid` in the if statement?

Comment (IvoJP) [reply packages/fxa-auth-server/lib/routes/account.ts:581]: yes because in order to get the payload you need to call `jwt.verify` so if for whatever reason that call were to throw an error (its within the `try` block) we dont want to attempt to drop their reminder. similarly if we did want to remove their reminder we dont want `jwt.verify` to potentially return the payload in the `try` block but not in the `catch` block and then not drop their reminder (if that all made sense). i also looked into how to rewrite this but ran up against the TS compiler. basically i wanted `uid` to be a shared variable between the try and catch block so if its set in one, its set in both.

Comment (StaberindeZA) [reply packages/fxa-auth-server/lib/routes/account.ts:581]: Yikes, I somehow missed the try/catch. Sorry about that.

**Review by StaberindeZA — APPROVED** [review]
LGTM
