### PR TITLE
fix(test): Fix the oauth choose redirect test

### LINKED ISSUE #1353: Failing functional test: oauth choose redirect - oauth endpoint redirects to signup with an unregistered email
See https://circleci.com/gh/mozilla/fxa/26986#tests/containers/0

Found in #1337 

> Screenshot saved at: https://screencap.co.uk/images/06b222d8d79d11cf79da5b65d60400d6ad031060.png
> firefox on linux 4.15.0-1035-aws - oauth choose redirect - oauth endpoint redirects to signup with an unregistered email (21.044s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/56437a18-a672-4970-80e4-0186e28676e7/element / {"using":"css selector","value":"#fxa-signup-header"}] Unable to locate element: #fxa-signup-header
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
    System info: host: '044ad43c4970', ip: '172.24.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-aws', java.version: '1.8.0_212'
    Driver info: driver.version: unknown
      at Command.<anonymous>  <tests/functional/lib/helpers.js:167:6>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:60:23>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:73:18>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:68:10>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:1221:6>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:60:23>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:1223:6>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:60:23>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:68:10>
      at Test.oauth endpoint redirects to signup with an unregistered email [as test]  <tests/functional/oauth_choose_redirect.js:44:10>
      at <src/lib/Test.ts:263:51>

The client_id looks invalid.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Open FxA from the RP and then use the client_id returned
from there.

fixes #1353

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@mozilla/fxa-devs - r?

File: packages/fxa-content-server/tests/functional/oauth_choose_redirect.js [hunk 1]
```diff
@@ -7,51 +7,50 @@
...
 registerSuite('oauth choose redirect', {
   beforeEach: function () {
     email = TestHelpers.createEmail();
 
-    return this.remote.then(clearBrowserState());
+    return this.remote
+      .then(clearBrowserState())
+      .then(openFxaFromRp('signup'))
+      .then(getQueryParamValue('client_id'))
+      .then(function (clientId) {
```
Comment (vladikoff) [inline packages/fxa-content-server/tests/functional/oauth_choose_redirect.js]: `() =>` ?
