### PR TITLE
fix(auth): handle paypal refused errors

### LINKED ISSUE #11592: Catch paypal transaction refund errors
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11352374/?referrer=github_plugin

```
WError: An internal server error occurred
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/paypal-client.js", line 146, in PayPalClient.doRequest
    throw new PayPalClientError(result.text, resultObj);
  ?, in runMicrotasks
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/paypal.js", line 334, in async PayPalHelper.refundTransaction
    const response = await this.client.refundTransaction(options);
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/paypal.js", line 342, in async PayPalHelper.issueRefund
    const refundResponse = await this.refundTransaction({
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.js", line 178, in async StripeWebhookHandler.handleCreditNoteEvent
    await this.paypalHelper.issueRefund(invoice, transactionId);
...
(7 additional frame(s) were not displayed)
```

The specific errors in this case can be determined by looking at the long message returned in the error. There are two to catch in this case:
- 'This transaction already has a chargeback filed'
- 'You are over the time limit to perform a refund on this transaction'

These should result in updating the invoice with new metadata to indicate why the refund cannot proceed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4425)

### PR DESCRIPTION
**Pull request by bbangert**
Because:

* We want to update the invoice for support if the paypal refund
  is refused.

This commit:

* Updates the credit note webhook handler so that if the paypal refund
  is refused, the invoice metadata will be updated to reflect why.

Closes #11592

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

File: packages/fxa-auth-server/lib/payments/paypal/error.ts [hunk 1]
```diff
@@ -0,0 +1,12 @@
+export class PaypalFailure extends Error {}
```
Comment (chenba) [inline packages/fxa-auth-server/lib/payments/paypal/error.ts:1]: A type alias for future use because you are going to add more `PaypalFailure`s?

File: packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts [hunk 2]
```diff
@@ -314,7 +314,16 @@ export class StripeWebhookHandler extends StripeHandler {
...
-    await this.paypalHelper.issueRefund(invoice, transactionId);
+    try {
+      await this.paypalHelper.issueRefund(invoice, transactionId);
+    } catch (error) {
+      if (error instanceof RefusedError) {
+        await this.stripeHelper.updateInvoiceWithPaypalRefundReason(
+          invoice,
+          error.longMessage
+        );
+      }
```
Comment (chenba) [inline packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts:325]: If we don't re-throw here for all the other types of errors, then this behavior is quite different than what we had previously.

Comment (biancadanforth) [inline packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts:325]: Did we want to catch all refused errors, or only the two with the particular long messages mentioned in the ticket?

> The specific errors in this case can be determined by looking at the long message returned in the error.
> There are two to catch in this case:
> * 'This transaction already has a chargeback filed'
> * 'You are over the time limit to perform a refund on this transaction'

File: packages/fxa-auth-server/lib/payments/paypal/error.ts (hunk 1 above)
Comment (bbangert) [reply packages/fxa-auth-server/lib/payments/paypal/error.ts:1]: Yep, and a single inheritance point as well.

File: packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts (hunk 2 above)
Comment (bbangert) [reply packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts:325]: All refused errors, this will include the long message on the invoice, so the support person can identify why it didn't work as well.

Comment (bbangert) [reply packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts:325]: Ah, yes, added that.
