### PR TITLE
fix(oauth): Revoke access tokens when revoking a refresh token

### LINKED ISSUE #1249: Destroying a `refresh_token` should destroy all `access_tokens` that were created from it
Ref https://github.com/mozilla/blurts-server/issues/992#issuecomment-495366822

If an RP destroys their refresh token, they might still have some active access tokens, and hence might still show up in the "devices and apps" list despite considering themselves "signed out".

It seems reasonable to me that destroying a `refresh_token` should also destroy any `access_tokens` that were created from it.

Implementing this would be complicated by two things:
* We don't currently link access tokens back to their originating refresh token, if any
* We're trying to reduce the lifetime of access tokens, and if the lifetime gets sufficiently small, perhaps there's no benefit to explicitly revoking them at all.

### LINKED ISSUE #3017: It takes two "Revoke" clicks to actually revoke device access
## Description

When I go to the FxA settings page to revoke access, it takes two clicks of the Revoke button to actually revoke.

### Steps to reproduce

- Sign into a site/app that uses FxA. https://monitor.firefox.com/ for example
- Go to https://accounts.firefox.com/settings
- Expand "Devices & apps"
- Click "Revoke" button for the site. "Firefox Monitor Last active a few seconds ago", for example.
- Click the "Refresh status" button below. The site revoked reappears.
- Click "Revoke button again". Now it's gone for good.

Screen recording: https://cl.ly/e8a6daf57bb6

### Expected result

It should take one click to revoke a site.

### Actual result

It takes two clicks

### Environment

I've  consistently seen this on stage and prod.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
All access tokens for a client_id, uid pair are revoked whenever
revoking a refresh token to avoid phantom entries in the
user's devices & apps list.

Before this PR, the problem was revoking a refresh token would
only revoke the refresh token and none of the access tokens created
from it. This led to a user revoking a refresh token, but then
the access tokens created from it showing up in the user's devices
& apps list, and needing to revoke those separately.

Because we don't associate access tokens and refresh tokens, we can't
delete just the access token associated with the refresh token. Instead,
this PR uses a blunt instrument and revokes *all* the access tokens
for the user/client_id. If the user has multiple active refresh tokens,
then the clients will use those refresh tokens to get new access
tokens for the ones that were revoked prematurely.

fixes #1249
fixes #3017 

@vladikoff, @vbudhram, @rfk - r?

### CODE REVIEW

File: packages/123done/oauth.js [hunk 1]
```diff
@@ -48,6 +48,7 @@ function verifyIdToken(oauthConfig, token) {
 
 function setupOAuthFlow(req, action, options = {}, cb) {
   var params = {
+    access_type: 'offline',
```
Comment (shane-tomlinson) [inline packages/123done/oauth.js]: I added this so that 123done would receive refresh tokens and we could add a functional test to the content server to ensure this is fixed.

File: packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/index.js [hunk 2]
```diff
@@ -606,12 +614,22 @@ MysqlStore.prototype = {
...
+      DELETE_ACTIVE_TOKENS_BY_CLIENT_AND_UID,
+      [buf(clientId), buf(uid)]
+    );
+
+    const deleteRefreshTokens = this._write(
+      DELETE_REFRESH_TOKEN_WITH_CLIENT_AND_UID,
+      [buf(refreshTokenId), buf(clientId), buf(uid)]
+    );
+
+    const [, refreshTokenRes] = await P.all([
```
Comment (vbudhram) [inline packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/index.js]: Should this be done in parallel? Is there a scenario where deleting a refresh tokens could fail and we don't want to delete access tokens?

Since this is parallel it is more performant though.

File: packages/fxa-auth-server/fxa-oauth-server/test/db/index.js [hunk 3]
```diff
@@ -623,4 +623,59 @@ describe('db', function() {
...
+      );
+      assert.isTrue(wasRevoked);
+
+      assert.notOk(await db.getRefreshToken(refreshTokenIdHash));
+
+      // all access tokens for the client_id, uid should be revoked as well
+      // as the refresh token. Clients that do the right thing will use
+      // active refresh tokens to get new access tokens for the ones that
+      // have been revoked. Deleting all the access tokens is to prevent
+      // ghost access tokesn from appearing in the user's devices & apps list.
```
Comment (vbudhram) [inline packages/fxa-auth-server/fxa-oauth-server/test/db/index.js]: nit: `tokesn` -> `tokens`

File: packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/index.js (hunk 2 above)
Comment (shane-tomlinson) [reply packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/index.js]: Good suggestion. This is a pretty low traffic route, so doing those serially should be fine.

**Comment by dannycoates** [comment]
TODO port to #2757
