### PR TITLE
fix(metrics): Add account recovery key flowEvents -> amplitudeEvents mapping

### LINKED ISSUE #4402: Create Amplitude Versions of Recovery Key Flow Metrics
We currently log some recovery key metrics as flow events, but they would be easier to use if they were also logged to amplitude. I propose we create the following mapping of flow events to amplitude events:

|flow event|amplitude event| 
|-- | --|
|  flow.account-recovery-confirm-key.view|  fxa_pref - account_recovery_confirm_view   |
|  flow.account-recovery-confirm-key.engage|  fxa_pref - account_recovery_confirm_enage   |
|  flow.account-recovery-confirm-key.submit|  fxa_pref - account_recovery_confirm_submit   |
|  flow.account-recovery-confirm-key.success|  fxa_pref - account_recovery_confirm_success   |
| flow.account-recovery-reset-password.view | fxa_login - forgot_password_recovery_key_view| 
| flow.account-recovery-reset-password.engage | fxa_login - forgot_password_recovery_key_engage|
|flow.account-recovery-reset-password.submit | fxa_login - forgot_password_recovery_key_submit|
| flow.account-recovery-reset-password.recovery-key-consume.success | fxa_login - forgot_password_recovery_key_success|

CC @davismtl @vbudhram

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1284)
┆Issue Number: FXA-1284

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #4402 

Marking as draft to see if any tests break.

To test go through the flow and view logs for content-server `./pm2 logs 11 | grep 'amplitudeEvent'`

Amplitude events for creating recovery key
```
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - add_recovery_key_view","time":1583346618519,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - add_recovery_key_submit","time":1583346619680,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - recovery_key_confirm_password_view","time":1583346619729,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - recovery_key_confirm_password_engage","time":1583346621129,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - recovery_key_confirm_password_submit","time":1583346623105,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - recovery_key_confirm_password_success","time":1583346623515,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - save_recovery_key_view","time":1583346623533,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - save_recovery_key_download","time":1583346625179,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - save_recovery_key_copy","time":1583346627089,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - save_recovery_key_print","time":1583346629358,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - save_recovery_key_submit","time":1583346634186,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - confirm_recovery_key_view","time":1583346634241,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - confirm_recovery_key_engage","time":1583346634959,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync","account_recovery":true}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - confirm_recovery_key_submit","time":1583346635489,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync","account_recovery":true}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - confirm_recovery_key_success","time":1583346635513,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync","account_recovery":true}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - verified_recovery_key_view","time":1583346635531,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync","account_recovery":true}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - verified_recovery_key_submit","time":1583346636712,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync","experiments":["send_sms_us"],"account_recovery":true}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_connect_device - view","time":1583346636784,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync","connect_device_flow":"sms"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync","experiments":["send_sms_us"],"account_recovery":true}}}
```

Ampitude events for consuming recovery key
```
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_login - forgot_password_confirm_recovery_key_view","time":1583348912601,"device_id":"138ae7a82e55421e9e1fdcc308787b70","session_id":1583348681386,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"6c0d4fb2d22a2bb6bd7dbc482b481654d10674e3014a4e4a1722e531bbc91549","ua_browser":"Firefox","ua_version":"72.0","utm_campaign":"fx-forgot-password","utm_content":"fx-reset-password","utm_medium":"email","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_login - forgot_password_confirm_recovery_key_engage","time":1583348919881,"device_id":"138ae7a82e55421e9e1fdcc308787b70","session_id":1583348681386,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"6c0d4fb2d22a2bb6bd7dbc482b481654d10674e3014a4e4a1722e531bbc91549","ua_browser":"Firefox","ua_version":"72.0","utm_campaign":"fx-forgot-password","utm_content":"fx-reset-password","utm_medium":"email","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_login - forgot_password_confirm_recovery_key_submit","time":1583348920760,"device_id":"138ae7a82e55421e9e1fdcc308787b70","session_id":1583348681386,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"6c0d4fb2d22a2bb6bd7dbc482b481654d10674e3014a4e4a1722e531bbc91549","ua_browser":"Firefox","ua_version":"72.0","utm_campaign":"fx-forgot-password","utm_content":"fx-reset-password","utm_medium":"email","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_login - forgot_password_recovery_key_view","time":1583348920956,"device_id":"138ae7a82e55421e9e1fdcc308787b70","session_id":1583348681386,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"6c0d4fb2d22a2bb6bd7dbc482b481654d10674e3014a4e4a1722e531bbc91549","ua_browser":"Firefox","ua_version":"72.0","utm_campaign":"fx-forgot-password","utm_content":"fx-reset-password","utm_medium":"email","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_login - forgot_password_recovery_key_engage","time":1583348929409,"device_id":"138ae7a82e55421e9e1fdcc308787b70","session_id":1583348681386,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"6c0d4fb2d22a2bb6bd7dbc482b481654d10674e3014a4e4a1722e531bbc91549","ua_browser":"Firefox","ua_version":"72.0","utm_campaign":"fx-forgot-password","utm_content":"fx-reset-password","utm_medium":"email","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_login - forgot_password_recovery_key_submit","time":1583348933767,"device_id":"138ae7a82e55421e9e1fdcc308787b70","session_id":1583348681386,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"6c0d4fb2d22a2bb6bd7dbc482b481654d10674e3014a4e4a1722e531bbc91549","ua_browser":"Firefox","ua_version":"72.0","utm_campaign":"fx-forgot-password","utm_content":"fx-reset-password","utm_medium":"email","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_login - forgot_password_recovery_key_success","time":1583348934361,"device_id":"138ae7a82e55421e9e1fdcc308787b70","session_id":1583348681386,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"6c0d4fb2d22a2bb6bd7dbc482b481654d10674e3014a4e4a1722e531bbc91549","ua_browser":"Firefox","ua_version":"72.0","utm_campaign":"fx-forgot-password","utm_content":"fx-reset-password","utm_medium":"email","$append":{"fxa_services_used":"sync","account_recovery":false}}}
```

### CODE REVIEW

**Comment by vbudhram** [comment]
@irrationalagent One thing I was not sure about here is if we should use the `fxa_pref` value. So it might make sense to use something different from enabling it via settings page?

**Comment by irrationalagent** [comment]
@davismtl do you have a preference here?

my thinking is that even though parts of this may not happen strictly within settings, the user is still setting a preference on their account, thus `fxa_pref`.

if we wanted to change it, perhaps `fxa_recovery` might work. but, that would mean creating a whole new category. ive aimed to re-use existing ones in the past, but maybe this may be a time to create a new one.

**Comment by vbudhram** [comment]
> my thinking is that even though parts of this may not happen strictly within settings, the user is still setting a preference on their account, thus fxa_pref.

Sounds reasonable to me! I'll mark this for review and will merge unless any objections from Alex.

File: packages/fxa-content-server/server/lib/amplitude.js [hunk 1]
```diff
@@ -101,6 +101,115 @@ const EVENTS = {
     event: 'signup_code_submit',
   },
 
+  // Add recovery key metrics
```
Comment (vbudhram) [inline packages/fxa-content-server/server/lib/amplitude.js]: There are no specific test cases for these because the test cases are generic for amplitudeEvents.

**Comment by davismtl** [comment]
> my thinking is that even though parts of this may not happen strictly within settings, the user is still setting a preference on their account, thus fxa_pref.

From what I can tell from that list of events, that seems to make sense.
