### PR TITLE
fix(auth-server): rewrite subhub msg processor

### LINKED ISSUE #2851: Cancelled subscription is still available under the subscriptions endpoint
## Description
The subscription endpoint returns a subscription even though it's already cancelled and it's not available in the UI. The userinfo endpoint though does not return any subscriptions.

### Steps to reproduce

* Cancel the guardian subscription in the FxA staging environment.
* Verify that there are not any subscriptions through the FxA account management.
* curl -v -H "Authorization: Bearer access_token" https://profile.stage.mozaws.net/v1/profile
   returns no subscriptions
* curl -v -H "Authorization: Bearer access_token" https://profile.stage.mozaws.net/v1/subscriptions
  returns `{"subscriptions": ["subscription_capability"]}`

### Expected result

The /subscriptions endpoint should not return any subscriptions

### Actual result

A subscription capability is returned.

### PR DESCRIPTION
**Pull request by bbangert**
Because:

* The existing subhub processor had multiple states it failed to
  account for.
* Profile cache locations were not updated.

This commit:

* Clears the profile cache and notifies that the profile was updated.
* Handles cancelled subscription state.
* Refactors subhub processor for less closure indents.

Closes #2851

### CODE REVIEW

File: packages/fxa-auth-server/lib/subhub/updates.js [hunk 1]
```diff
@@ -6,19 +6,22 @@
...
-    .integer()
-    .required(),
-  del: Joi.any(), // a method (function) that's added to messages
-});
+const MESSAGE_SCHEMA = Joi.object()
+  .keys({
+    uid: Joi.string().required(),
+    active: Joi.boolean().required(),
+    subscriptionId: Joi.string().required(),
+    productId: Joi.string(),
```
Comment (lmorchard) [inline packages/fxa-auth-server/lib/subhub/updates.js]: :+1:

File: packages/fxa-auth-server/lib/subhub/updates.js [hunk 2]
```diff
@@ -28,91 +31,146 @@ function validateMessage(message) {
...
+      } else if (existing) {
+        // Existing account is already active.
+      } else {
+        await this.db.createAccountSubscription({
           uid,
-          action: 'error',
-          err,
-          stack: err && err.stack,
+          subscriptionId: message.subscriptionId,
+          productId: message.productId,
```
Comment (lmorchard) [inline packages/fxa-auth-server/lib/subhub/updates.js]: :+1:

File: packages/fxa-auth-server/lib/subhub/updates.js [hunk 3]
```diff
@@ -28,91 +31,146 @@ function validateMessage(message) {
...
+   */
+  async updateSystems(uid, message) {
+    await this.profile.deleteCache(uid);
+    await this.push.notifyProfileUpdated(uid);
+    await this.log.notifyAttachedServices('subscription:update', MOCK_REQUEST, {
+      uid,
+      eventCreatedAt: message.eventCreatedAt,
+      subscriptionId: message.subscriptionId,
+      isActive: message.active,
+      productId: message.productId,
```
Comment (lmorchard) [inline packages/fxa-auth-server/lib/subhub/updates.js]: :+1:

**Comment by lmorchard** [comment]
FWIW, I believe this also fixes issue #2799
