### PR TITLE
fix(delete-account): Include subscription status filtering for 'trialing' and 'past_due'

### LINKED ISSUE #4166: (fxa-content-server) Update 'delete_account' subscription filtering to include 'trialing' and 'past_due'
In the delete_account view, we filter subscriptions in `_fetchActiveSubscriptions` as well as `_getNumberOfProducts` for those that match `.status === 'active'`. We should also include those with a status of 'trialing' and 'past_due'.

We could also update the endpoint we hit here to `subscriptions/active` but it's probably not worth the effort as we would still need to filter out subscriptions with a status of 'canceled'.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1116)
┆Issue Number: FXA-1116

### PR DESCRIPTION
**Pull request by LZoog**
fixes #4166

@mozilla/fxa-devs r?

### CODE REVIEW

File: packages/fxa-content-server/app/scripts/views/settings/delete_account.js [hunk 1]
```diff
@@ -121,19 +121,14 @@ var View = FormView.extend({
...
       if (client.isOAuthApp === true) {
         numberOfProducts++;
       }
     }
-    // eslint-disable-next-line no-unused-vars
-    for (const sub of this._activeSubscriptions) {
-      if (sub.plan_id && sub.status === 'active') {
-        numberOfProducts++;
-      }
-    }
```
Comment (LZoog) [inline packages/fxa-content-server/app/scripts/views/settings/delete_account.js]: We call `_getNumberOfProducts` after we filter subscriptions in `_fetchActiveSubscriptions` and set `_activeSubscriptions` so we should be able to set the number on the `.length` of the array instead of filtering through again.

File: packages/fxa-content-server/app/tests/spec/views/settings/delete_account.js [hunk 2]
```diff
@@ -26,7 +26,7 @@ describe('views/settings/delete_account', function() {
   const UID = '123';
   const password = 'password';
   let account;
-  let activeSubscriptions;
+  let subscriptions;
```
Comment (LZoog) [inline packages/fxa-content-server/app/tests/spec/views/settings/delete_account.js]: I changed this var name as `subscriptions` is more accurate since it's the mock return for  `account.settingsData()`, before we've filtered for active subscriptions.

File: packages/fxa-content-server/app/tests/spec/views/settings/delete_account.js [hunk 3]
```diff
@@ -398,20 +406,8 @@ describe('views/settings/delete_account', function() {
         );
       });
 
-      it('renders only `active: true` subscriptions', () => {
-        assert.lengthOf(view.$('.delete-account-product-subscription'), 1);
-      });
-
-      it('renders subscription title attributes', () => {
```
Comment (LZoog) [inline packages/fxa-content-server/app/tests/spec/views/settings/delete_account.js]: We had a couple of duplicate tests here that I removed, we're still testing subscription title attributes on line 377 and testing for active subscriptions on line 373.
