### PR TITLE
fix(l10n): fix primary email update message l10n

### LINKED ISSUE #5136: "Primary email set to %(email)s" is not localized
It looks like the first string in #3258 did not get addressed in #3319, I’ve just seen it popping n English. Filing this issue to get it back in the backlog

Capture d’écran 2020-04-28 à 18 38 40

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1776)
┆Issue Number: FXA-1776

### PR DESCRIPTION
**Pull request by chenba**
Fixes #5136 (FXA-1776)

### CODE REVIEW

File: packages/fxa-content-server/app/scripts/views/settings/emails.js [hunk 1]
```diff
@@ -187,7 +186,7 @@ var View = FormView.extend({
       account.unset('originalLoginEmail');
       this.setSearchString('email', email);
       this.displaySuccess(
-        Strings.interpolate(t('Primary email set to %(email)s'), { email }),
+        this.translate(t('Primary email set to %(email)s'), { email }),
```
Comment (lmorchard) [inline packages/fxa-content-server/app/scripts/views/settings/emails.js:189]: Huh. Do we know why this stopped working? The code looks not recently changed here. Also... do we happen to have a test that could have caught this?

Comment (chenba) [reply packages/fxa-content-server/app/scripts/views/settings/emails.js:189]: > 
> 
> Huh. Do we know why this stopped working? The code looks not recently changed here. 

It is possible that this never worked.  The user has to a) add a secondary email, b) set the secondary as the primary, c) pay attention the notification message, d) know to expect a localized message, and e) report a bug.  It was originally reported in #3258, but it was not fixed in the PR.

> Also... do we happen to have a test that could have caught this?

Off hand I don't remember how many tests we have for testing specific message l10n.  I'll dig around a bit.

Comment (chenba) [reply packages/fxa-content-server/app/scripts/views/settings/emails.js:189]: The view translator actually has a test specific argument (https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/lib/translator.js#L17) so it won't try to fetch translations.

I updated the view test to ensure that the correct function is called with the correct arguments.
