### PR TITLE
Fix flaky OAuth test

### LINKED ISSUE #1837: Intermittent oauth server test failure:  `POST /authorized-clients should seperately list different refresh tokens from the same client`
Maybe 1 in 3 or 1 in 4 times I run the oauth server tests, this happens from api.js:

```
 1) /v1
       /authorized-clients
         POST /authorized-clients
           should seperately list different refresh tokens from the same client:

      AssertionError: expected [ 'other', 'scope' ] to deeply equal [ 'profile' ]
      + expected - actual

       [
      -  "other"
      -  "scope"
      +  "profile"
       ]
```

### PR DESCRIPTION
**Pull request by rfk**
Fixes #1837, in which a test would sometimes pass if two tokens had the same timestamp (causing them to be sorted by scope values) and would sometimes fail if they did not. The scope values now produce the same sort order as the timestamps.

### CODE REVIEW

File: packages/fxa-auth-server/fxa-oauth-server/lib/routes/authorized-clients/list.js [hunk 1]
```diff
@@ -127,10 +127,10 @@ module.exports = {
         return -1;
       }
       // To help provide a deterministic result order to simplify testing, also sort of scope values.
-      if (a.scope < b.scope) {
```
Comment (rfk) [inline packages/fxa-auth-server/fxa-oauth-server/lib/routes/authorized-clients/list.js]: These were accidentally sorting in reverse order, which seems needlessly confusing.

**Comment by philbooth** [comment]
Test failure is `cargo audit` in the email service, having a look at it now...

**Comment by philbooth** [comment]
> Test failure is `cargo audit` in the email service, having a look at it now...

*...eventually gets to @rfk's comment in the `crossbeam` issue thread, realises he's way behind...*

**Comment by philbooth** [comment]
> Test failure is `cargo audit` in the email service, having a look at it now...

https://github.com/mozilla/fxa/pull/1866

**Comment by rfk** [comment]
(rebased in the hope of unsticking CI)
